// FIN-EPIC-007: isolated sample facts; never a replacement for backend financial calculations.
export const days = [
  { date:'2026-09-13', kind:'quiet', title:'No activity recorded', activity:[], detail:'The sample has no recorded activity for this day. That does not prove zero spending.' },
  { date:'2026-09-14', kind:'quiet', title:'No activity recorded', activity:[], detail:'The sample has no recorded activity for this day. That does not prove zero spending.' },
  { date:'2026-09-15', kind:'bridge', label:'A little closer to the other side.', tag:'A STEP FORWARD', title:'A loan payment recorded', body:'₹8,000 was recorded toward your loan. You can review the payment below.', amount:8000, amountLabel:'Loan payment recorded', tree:0, bridge:1, savings:0, landmarks:false, activity:[['Loan payment',8000,'Confirmed sample repayment']], detail:'This stone represents one recorded repayment, not a percentage of the loan repaid. The bridge stays unfinished until loan closure is verified.' },
  { date:'2026-09-16', kind:'tree', label:'Small beginnings. Room to grow.', tag:'SOMETHING NEW', title:'Your first investment contribution', body:'You recorded ₹2,000 invested. This is the first contribution in your sample history.', amount:2000, amountLabel:'Investment contribution', tree:1, bridge:1, savings:0, landmarks:false, activity:[['Investment contribution',2000,'First contribution recorded']], detail:'This tree marks recorded contributions. It does not represent investment returns, market value, or a prediction of future growth.' },
  { date:'2026-09-17', kind:'life', label:'Money was part of living today.', tag:'THE EVERYDAY CHAPTER', title:'₹1,380 spent on everyday needs', body:'Groceries accounted for ₹1,200 and travel for ₹180 across two recorded expenses.', amount:1380, amountLabel:'Recorded expenses', tree:1, bridge:1, savings:0, landmarks:true, activity:[['Groceries',1200,'Food for home'],['Travel',180,'Getting across town']], detail:'Two recorded expenses total ₹1,380. These are recorded expenses, not a bank balance or a judgment about your spending.' },
  { date:'2026-09-18', kind:'shelter', label:'A little preparation for tomorrow.', tag:'MAKING ROOM', title:'Halfway to your insurance savings target', body:'You added ₹5,000 to your recorded savings. You now have ₹10,000 set aside toward ₹20,000; the insurance bill is still unpaid.', amount:5000, amountLabel:'Money set aside today', tree:1, bridge:1, savings:0.5, landmarks:true, activity:[['Car insurance savings',5000,'Money set aside · not an expense']], detail:'The sample plan has ₹10,000 recorded saved toward ₹20,000. Today’s ₹5,000 is part of that total. Insurance remains unpaid; this is savings progress only.' },
  { date:'2026-09-19', kind:'quiet', label:'A quiet stop along the way.', tag:'ROOM TO BREATHE', title:'No activity recorded', body:'There is no new story for this day. You can revisit another date or record an expense.', amount:null, amountLabel:'', tree:1, bridge:1, savings:0.5, landmarks:true, activity:[], detail:'No activity recorded does not mean nothing was spent. No new insight is generated from an absence of records.' },
  { date:'2026-09-20', kind:'bridge', label:'Another step on a familiar path.', tag:'KEEPING GOING', title:'Another loan payment recorded', body:'A second ₹8,000 payment is recorded in this sample history. Loan closure has not been confirmed.', amount:8000, amountLabel:'Loan payment recorded', tree:1, bridge:2, savings:0.5, landmarks:true, activity:[['Loan payment',8000,'Confirmed sample repayment']], detail:'Two sample repayments are now recorded. These are milestones, not an estimate of the remaining balance. The loan is not marked closed.' },
  { date:'2026-09-21', kind:'tree', label:'Look at what you’re growing.', tag:'A NEW BRANCH', title:'Your contributions reached ₹4,000', body:'You added ₹2,000 to your investments. Together with your first contribution, that brings your recorded contributions to ₹4,000.', amount:2000, amountLabel:'Investment contribution today', tree:2, bridge:2, savings:0.5, landmarks:true, activity:[['Investment contribution',2000,'Second contribution recorded']], detail:'Two contributions of ₹2,000 total ₹4,000 contributed. Tree growth reflects these recorded contributions, not investment performance. Visit 16 September to see the first sapling.' }
];
export const money = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:0,maximumFractionDigits:2}).format(value);
export const dayLabel = date => new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'long',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
export const weekday = date => new Intl.DateTimeFormat('en-IN',{weekday:'long',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
