package com.apps.deen_sa.conversation.interpretation;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class MutationAuthorizationPolicyTest {
    private final MutationAuthorizationPolicy policy = new MutationAuthorizationPolicy();

    @Test
    void authorizesTamilExpenseWhenAmountIsGroundedInCurrentMessage() {
        TurnInterpretation expense = expenseWithAmountEvidence("58");

        assertThat(policy.isAuthorized(expense, "தின்பண்டத்திற்கு 58 ரூபாய் செலவு செய்தேன்")).isTrue();
    }

    @Test
    void rejectsHistoryAmountCopiedIntoTamilQuestion() {
        TurnInterpretation leakedExpense = expenseWithAmountEvidence("58");

        assertThat(policy.isAuthorized(leakedExpense, "இன்று நான் எவ்வளவு செலவு செய்தேன்?")).isFalse();
    }

    @Test
    void authorizesExplicitAccountSetupWithoutTreatingOpeningBalanceAsTransactionAmount() {
        EventPatch account = new EventPatch(null, "ACCOUNT_SETUP", Map.of(
                "amount", 20000,
                "rawText", "Create my HDFC salary bank account with a current balance of 20000"
        ), List.of(), List.of(), List.of());
        TurnInterpretation setup = new TurnInterpretation(TurnType.NEW_EVENT, "ACCOUNT_SETUP", "en-IN", null,
                List.of(account), null, QueryPeriod.NONE, List.of(), 0.99);

        assertThat(policy.isAuthorized(setup,
                "Create my HDFC salary bank account with a current balance of 20000")).isTrue();
    }

    @Test
    void authorizesMultipleExpensesWhenEachAmountHasExactEvidence() {
        EventPatch tea = expense("80", "Spent 80 on tea");
        // Per-event rawText generated by the model need not be one contiguous slice of the combined sentence.
        EventPatch auto = expense("120", "Spent 120 on auto using UPI");
        TurnInterpretation expenses = new TurnInterpretation(TurnType.NEW_EVENTS, "EXPENSE", "en-IN", null,
                List.of(tea, auto), null, QueryPeriod.NONE, List.of(), 0.99);

        assertThat(policy.isAuthorized(expenses, "Spent 80 on tea and 120 on auto using UPI")).isTrue();
    }

    @Test
    void rejectsUngroundedAmountEvenWhenModelSuppliesParaphrasedRawText() {
        EventPatch invented = new EventPatch(null, "EXPENSE", Map.of(
                "amount", 999, "rawText", "Spent 999 on auto"
        ), List.of(), List.of(), List.of());
        TurnInterpretation expense = new TurnInterpretation(TurnType.NEW_EVENT, "EXPENSE", "en-IN", null,
                List.of(invented), null, QueryPeriod.NONE, List.of(), 0.99);

        assertThat(policy.isAuthorized(expense, "Spent money on auto")).isFalse();
    }

    @Test
    void authorizesExplicitNumericValuesWhenModelEvidenceWordingIsNotContiguous() {
        EventPatch tea = new EventPatch(null, "EXPENSE", Map.of("amount", 80.0, "rawText", "Spent 80 tea"),
                List.of(), List.of(), List.of(new FieldEvidence("amount", "80", "tea amount: 80", 0.99)));
        EventPatch auto = new EventPatch(null, "EXPENSE", Map.of("amount", 120.0, "rawText", "Spent 120 auto"),
                List.of(), List.of(), List.of(new FieldEvidence("amount", "120", "auto amount: 120", 0.99)));
        TurnInterpretation expenses = new TurnInterpretation(TurnType.NEW_EVENTS, "EXPENSE", "en-IN", null,
                List.of(tea, auto), null, QueryPeriod.NONE, List.of(), 0.99);

        assertThat(policy.isAuthorized(expenses, "Spent 80 on tea and 120 on auto using UPI")).isTrue();
    }

    @Test
    void numericGroundingUsesWholeTokensAndUnderstandsHumanAmountSuffixes() {
        assertThat(policy.isAuthorized(expenseWithAmountEvidence("not exact"), "I spent 158 today")).isFalse();

        EventPatch balance = new EventPatch(null, "ACCOUNT_SETUP", Map.of("amount", 10000),
                List.of(), List.of(), List.of());
        TurnInterpretation setup = new TurnInterpretation(TurnType.NEW_EVENT, "ACCOUNT_SETUP", "en-IN", null,
                List.of(balance), null, QueryPeriod.NONE, List.of(), 0.99);
        assertThat(policy.isAuthorized(setup, "Current balance is 10k")).isTrue();
    }

    private EventPatch expense(String amount, String rawText) {
        return new EventPatch(null, "EXPENSE", Map.of("amount", Integer.parseInt(amount), "rawText", rawText),
                List.of(), List.of(), List.of(new FieldEvidence("amount", amount, amount, 0.99)));
    }

    private TurnInterpretation expenseWithAmountEvidence(String evidence) {
        EventPatch event = new EventPatch(null, "EXPENSE", Map.of("amount", 58), List.of(), List.of(),
                List.of(new FieldEvidence("amount", "58", evidence, 0.99)));
        return new TurnInterpretation(TurnType.NEW_EVENT, "EXPENSE", "ta-IN", null,
                List.of(event), null, QueryPeriod.NONE, List.of(), 0.99);
    }
}
