<!-- FIN-EPIC-002, FIN-EPIC-003, and FIN-EPIC-005: see docs/jira/personal-expense/FIN-EPIC-002-correctness.md, FIN-EPIC-003-insights.md, and FIN-EPIC-005-planning.md -->
<script>
  import './commitment.css';
  import { onMount } from 'svelte';
  import { ApiError, completeAction, confirmSipOccurrence, createCreditCard, createLoan, createMissingDateContext, createMutualFund, createStock, createRecurringCommitment, deleteExpense, getActions, getCommitmentReview, getCreditCards, getExpenseOptions, getExpensesForDate, getIncomeOutlook, getLoans, getMutualFund, getMutualFunds, getRecurringCommitments, getStocks, logout, resolveCommitmentReview, saveIncomeProfile, searchMutualFunds, searchStocks, updateCreditCard, updateExpense, updateLoan, updateSipOccurrence } from './lib/api.js';
  import SectionState from './SectionState.svelte';
  import Normalization from './Normalization.svelte';
  import AppHeader from './components/AppHeader.svelte';
  import BottomNav from './components/BottomNav.svelte';
  import ProfileSettings from './features/profile/ProfileSettings.svelte';
  export let calendarSection; export let recentSection; export let storiesSection; export let selectedMonth; export let connectionStatus; export let cacheUpdatedAt; export let demoMode; export let onDemoModeChange; export let onMonthChange; export let refreshCalendar; export let refreshRecent; export let refreshStories; export let onRetryConnection; export let onLogout;

  let view='home', showMoney=false, showNormalization=false, selectedDay=null, activityTab='recent', dayItems=[], dayStatus='idle', showAll=false, expandedId=null;
  let openedStory=null, handoff=null, addingContext=false, actionError='', loggingOut=false, signOutError='', demoSwitching=false, demoError='', storySlide=0, storyTouchStart=null, showStoryEvidence=false, storyFilter='All', homeStoryIndex=0, storiesRailIndex=0, storyRailTouchStart=null;
  let commitmentStyle='playful';
  let editing=null, editAmount='', editDate='', editCategory='', editSubcategory='', editMerchantId='', editAccountId='', saving=false, deleting=null;
  let editOptions={categories:[],merchants:[],accounts:[]}, optionsStatus='idle', optionsError='';
  let storyControls={spending:true,investments:true,planning:true};
  let showLoanForm=false, loanError='', loanStatus='idle', loanEditingId=null, loanSaving=false;
  let loanForm={loanName:'',loanType:'HOME',lenderName:'',originalPrincipal:'',monthlyEmiAmount:'',totalTenureMonths:'',firstEmiDueDate:'',notes:''};
  let loans=[];
  let commitments=[], commitmentStatus='idle', commitmentError='', showCommitmentForm=false, commitmentSaving=false;
  let commitmentForm={label:'',planningAmount:'',dueDay:'',amountMode:'FIXED'};
  let creditCards=[], creditCardStatus='idle', creditCardError='', showCreditCardForm=false, creditCardSaving=false, creditCardEditingId=null;
  let creditCardForm={accountReferenceId:'',cardName:'',issuerName:'',statementDay:'',dueDay:''};
  let showCommitmentReview=false, commitmentReview=[], commitmentReviewStatus='idle', resolvingCandidate=null;
  let incomeOutlook={salary:null}, incomeStatus='idle', incomeError='', incomeSaving=false, showIncomeFlow=false;
  let salaryForm={salaryVisibility:'RANGE',salaryRange:'FROM_50000_TO_100000',exactMonthlySalary:'',salaryFrequency:'MONTHLY'};
  let showMutualFundForm=false, schemeQuery='', showSchemeMenu=false, selectedScheme=null, fundError='', fundSaved=false, fundSaving=false, schemeSearchStatus='idle', schemeResults=[], schemeSearchRequest=0;
  let mutualFunds=[], mutualFundStatus='idle', mutualFundError='';
  let stocks=[], stockStatus='idle', stockError='', showStockForm=false, stockQuery='', selectedStock=null, stockResults=[], stockSearchStatus='idle', stockSearchRequest=0, stockSaving=false;
  let stockForm={quantity:'',totalInvested:''};
  let actions=[], actionsStatus='idle', actionsError='', completingActionId=null;
  let confirmingSip=null, sipConfirmError='', sipConfirmSaving=false, sipConfirmForm={amount:'',transactionDate:new Date().toISOString().slice(0,10),nav:''};
  let fundDetail=null, fundDetailStatus='idle', fundDetailError='';
  const MONEY_MODULES_CACHE_KEY='money-stories.money-modules-cache.v1';
  let fundForm={sipAmount:'25000',sipDate:'5',startMonth:'2026-10',paymentMethod:'AUTOPAY',hasHolding:'YES',currentUnits:'128.456',totalInvested:'10000'};
  $: data=calendarSection.data||{}; $: currency=data.currency||'INR'; $: calendar=buildCalendar(selectedMonth,data.days||[]);
  $: recentData=recentSection.data||{}; $: recentItems=(recentData.items||recentData.expenses||[]).slice(0,5);
  $: storyData=storiesSection.data||{}; $: stories=storyData.stories||storyData.moneyStories||storyData.storyCards||[];
  $: filteredStories=storyFilter==='All'?stories:stories.filter(story=>storySource(story).toLowerCase()===storyFilter.toLowerCase());
  $: homeStories=stories.slice(0,3);
  $: if(homeStoryIndex>=homeStories.length)homeStoryIndex=0;
  $: if(storiesRailIndex>=filteredStories.length)storiesRailIndex=0;
  $: selected=selectedDay==null?null:calendar.days.find(day=>day.day===selectedDay); $: activeItems=activityTab==='recent'?recentItems:dayItems; $: visibleItems=showAll?activeItems:activeItems.slice(0,5);
  $: editSubcategories=editOptions.categories.find(option=>option.name===editCategory)?.subcategories||[];
  $: totalMonthlyEmi=loans.reduce((total,loan)=>total+Number(loan.monthlyEmiAmount||0),0);
  $: mutualPortfolio={invested:mutualFunds.reduce((total,fund)=>total+Number(fund.invested||0),0),current:mutualFunds.some(fund=>fund.currentValue!==null)?mutualFunds.reduce((total,fund)=>total+Number(fund.currentValue||0),0):null,pnl:mutualFunds.some(fund=>fund.profitOrLoss!==null)?mutualFunds.reduce((total,fund)=>total+Number(fund.profitOrLoss||0),0):null};
  $: stockPortfolio={invested:stocks.reduce((total,stock)=>total+Number(stock.invested||0),0),current:stocks.some(stock=>stock.currentValue!==null)?stocks.reduce((total,stock)=>total+Number(stock.currentValue||0),0):null,pnl:stocks.some(stock=>stock.profitOrLoss!==null)?stocks.reduce((total,stock)=>total+Number(stock.profitOrLoss||0),0):null};
  $: visibleActions=actions.map(action=>({action,presentation:actionPresentation(action)})).filter(item=>item.presentation);
  const money=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency,maximumFractionDigits:0}).format(Number(value||0));
  const moneyDecimal=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency,minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value||0));
  const compactMoney=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency,notation:'compact',maximumFractionDigits:2}).format(Number(value||0));
  const fundSubtitle=name=>/growth/i.test(name)?'Growth · Direct plan':'Verified scheme'; const fundAccent=id=>['coral','gold','violet','blue'][Number(id||0)%4];
  const merchant=item=>item.merchant||item.merchantName||item.description||item.originalMessage||'Expense'; const category=item=>item.category?.name||item.category||'Uncategorised'; const transactionDate=item=>item.transactionDate||item.transactionTime||item.date;
  const dateLabel=value=>value?new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short'}).format(new Date(value)):'';
  const monthLabel=value=>{const[y,m]=value.split('-').map(Number);return new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(new Date(y,m-1));};
  const greeting=()=>new Date().getHours()<12?'Good morning':new Date().getHours()<17?'Good afternoon':'Good evening'; const isoDate=day=>`${selectedMonth}-${String(day).padStart(2,'0')}`;
  const hasDeck=story=>Array.isArray(story.cards)&&story.cards.length>0; const storyName=story=>String(story.storyType||story.type||'Money story').replaceAll('_',' '); const storyTone=story=>story.cardFace?.theme||'calm'; const storyCardFace=story=>story.cardFace||{heading:'Money story',displayValue:'View',theme:'calm'}; const storySource=story=>story.source||story.domain||(story.storyType==='MONTHLY_COMMITMENT'?'Planning':'Spending');
  const isCommitment=story=>story?.storyType==='MONTHLY_COMMITMENT'; const storyIcon=story=>isCommitment(story)?'🎬':''; const storyHeading=story=>storyCardFace(story).heading;
  function setCommitmentStyle(style){commitmentStyle=style;try{localStorage.setItem('money-stories.commitment-style',style);}catch{}}
  $: connectionLabel=connectionStatus==='online'?'Online':connectionStatus==='offline'?'Offline':'Checking';
  $: evidenceItems=evidenceFor(openedStory,storySlide);
  function localInputDate(value){if(!value)return '';const text=String(value);if(/^\d{4}-\d{2}-\d{2}$/.test(text))return text;const date=new Date(text);return Number.isNaN(date.getTime())?text.slice(0,10):`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
  function evidenceFor(story,slide=0){const card=story?.cards?.slice().sort((a,b)=>(a.sequence||0)-(b.sequence||0))[slide];const evidence=story?.evidence?.byCard?.[card?.cardId]||story?.evidence;const raw=Array.isArray(evidence)?evidence:evidence?.transactions||evidence?.items||story?.transactions||[];return raw.map(item=>({merchant:item.merchantLabel||item.merchant||item.merchantName||item.description||'Expense',category:item.categoryLabel||item.category?.name||item.category||'Uncategorised',detail:item.subcategoryLabel||item.detail||'',date:item.dateLabel||dateLabel(item.transactionDate||item.transactionTime||item.date),amount:item.amount?.displayValue||item.displayAmount||money(item.amount)}));}
  function loanSchedule(loan){const first=new Date(`${loan.firstEmiDueDate}T12:00:00`);if(Number.isNaN(first.getTime()))return null;const today=new Date(),tenure=Number(loan.totalTenureMonths)||0,elapsedMonths=(today.getFullYear()-first.getFullYear())*12+today.getMonth()-first.getMonth(),due=Math.max(0,Math.min(tenure,elapsedMonths+(today.getDate()>=first.getDate()?1:0))),remaining=Math.max(0,tenure-due),finalDue=new Date(first.getFullYear(),first.getMonth()+Math.max(0,tenure-1),first.getDate());return{due,remaining,tenure,percent:tenure?Math.round(due/tenure*100):0,endLabel:new Intl.DateTimeFormat(undefined,{month:'short',year:'numeric'}).format(finalDue)};}
  function actionPresentation(action){if(action.actionType==='LOAN_CLOSURE_CONFIRMATION'){const scheduled=action.scheduledCompletionDate?new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${action.scheduledCompletionDate}T12:00:00`)):'';const description=(action.description||`EMI was scheduled to finish on ${scheduled}.`).replace(action.scheduledCompletionDate||'',scheduled).replace(/\s*Mark it closed if the final EMI was paid\.?\s*$/i,'');return{title:'Loan closure confirmation',description,cta:'Mark loan closed'};}return null;}
  const moneyModulesCacheKey=()=>`${MONEY_MODULES_CACHE_KEY}.${demoMode?'demo':'real'}`;
  function readMoneyModulesCache(){try{const cached=JSON.parse(localStorage.getItem(moneyModulesCacheKey())||'null');if(!cached)return false;if(Array.isArray(cached.loans)){loans=cached.loans;loanStatus='ready';}if(Array.isArray(cached.mutualFunds)){mutualFunds=cached.mutualFunds;mutualFundStatus='ready';}if(Array.isArray(cached.stocks)){stocks=cached.stocks;stockStatus='ready';}return true;}catch{return false;}}
  function saveMoneyModulesCache(){try{localStorage.setItem(moneyModulesCacheKey(),JSON.stringify({updatedAt:new Date().toISOString(),loans,mutualFunds,stocks}));}catch{/* The live modules still work if storage is unavailable. */}}
  async function loadLoans(){loanStatus=loans.length?'refreshing':'loading';try{const result=await getLoans();loans=result.loans||[];loanStatus='ready';saveMoneyModulesCache();}catch(cause){if(loans.length){loanStatus='ready';return;}loanStatus='error';loanError=cause?.message||'Could not load loans.';}}
  async function loadCommitments(){commitmentStatus='loading';commitmentError='';try{const result=await getRecurringCommitments();commitments=result.items||[];commitmentStatus='ready';}catch(cause){commitmentStatus='error';commitmentError=cause?.message||'Could not load commitments.';}}
  function openCommitmentForm(item=null){commitmentError='';commitmentForm=item?{label:merchant(item),planningAmount:String(item.amount||''),dueDay:String(new Date(transactionDate(item)).getDate()||''),amountMode:'FIXED',sourceTransactionId:item.id}:{label:'',planningAmount:'',dueDay:'',amountMode:'FIXED'};showCommitmentForm=true;}
  async function saveCommitment(){const planningAmount=Number(commitmentForm.planningAmount),dueDay=commitmentForm.dueDay?Number(commitmentForm.dueDay):null;if(!commitmentForm.label.trim()||!(planningAmount>0)||dueDay!==null&&(dueDay<1||dueDay>28)){commitmentError='Add a name, a positive planning amount, and an optional due day from 1 to 28.';return;}commitmentSaving=true;try{await createRecurringCommitment({...commitmentForm,label:commitmentForm.label.trim(),planningAmount,dueDay,effectiveMonth:selectedMonth});showCommitmentForm=false;await Promise.all([loadCommitments(),refreshStories()]);}catch(cause){commitmentError=cause?.message||'Could not save this commitment.';}finally{commitmentSaving=false;}}
  async function loadMutualFunds(){mutualFundStatus=mutualFunds.length?'refreshing':'loading';mutualFundError='';try{const result=await getMutualFunds();mutualFunds=result.mutualFunds||[];mutualFundStatus='ready';saveMoneyModulesCache();}catch(cause){if(mutualFunds.length){mutualFundStatus='ready';return;}mutualFundStatus='error';mutualFundError=cause?.message||'Could not load mutual funds.';}}
  async function loadStocks(){stockStatus=stocks.length?'refreshing':'loading';stockError='';try{const result=await getStocks();stocks=result.stocks||[];stockStatus='ready';saveMoneyModulesCache();}catch(cause){if(stocks.length){stockStatus='ready';return;}stockStatus='error';stockError=cause?.message||'Could not load stocks.';}}
  async function loadActions(){actionsStatus=actions.length?'refreshing':'loading';actionsError='';try{const result=await getActions();actions=result.actions||[];actionsStatus='ready';}catch(cause){actionsStatus='error';actionsError=cause?.message||'Could not load actions.';}}
  async function completeOpenAction(action){if(completingActionId!==null)return;completingActionId=action.id;actionsError='';try{await completeAction(action.id);actions=actions.filter(item=>item.id!==action.id);await Promise.all([loadLoans(),loadActions()]);}catch(cause){actionsError=cause?.message||'Could not complete this action.';}finally{completingActionId=null;}}
  const incomeRangeLabel=value=>({UNDER_25000:'Under ₹25k',FROM_25000_TO_50000:'₹25k–₹50k',FROM_50000_TO_100000:'₹50k–₹1L',FROM_100000_TO_200000:'₹1L–₹2L',OVER_200000:'Over ₹2L'})[value]||'Not shared';
  async function loadIncomeOutlook(){incomeStatus='loading';incomeError='';try{incomeOutlook=await getIncomeOutlook();incomeStatus='ready';}catch(cause){incomeStatus='error';incomeError=cause?.message||'Could not load your income outlook.';}}
  async function openMoney(){showMoney=true;readMoneyModulesCache();await Promise.all([loadLoans(),loadMutualFunds(),loadStocks(),loadIncomeOutlook(),loadCommitments(),loadCreditCards(),loadExpenseOptions()]);}
  async function loadCreditCards(){creditCardStatus='loading';creditCardError='';try{const result=await getCreditCards();creditCards=result.cards||[];creditCardStatus='ready';}catch(cause){creditCardStatus='error';creditCardError=cause?.message||'Could not load credit cards.';}}
  async function loadExpenseOptions(){if(optionsStatus==='loading')return;try{const result=await getExpenseOptions();editOptions={categories:result.categories||[],merchants:result.merchants||[],accounts:result.accounts||[]};optionsStatus='ready';}catch(cause){optionsStatus='error';optionsError=cause?.message||'Could not load accounts.';}}
  function openCreditCardForm(card=null){creditCardError='';creditCardEditingId=card?.id??null;creditCardForm=card?{accountReferenceId:String(card.accountReferenceId),cardName:card.cardName,issuerName:card.issuerName,statementDay:String(card.statementDay),dueDay:String(card.dueDay)}:{accountReferenceId:'',cardName:'',issuerName:'',statementDay:'',dueDay:''};showCreditCardForm=true;}
  async function saveCreditCard(){const statementDay=Number(creditCardForm.statementDay),dueDay=Number(creditCardForm.dueDay);if(!creditCardForm.accountReferenceId||!creditCardForm.cardName.trim()||!creditCardForm.issuerName.trim()||statementDay<1||statementDay>28||dueDay<1||dueDay>28){creditCardError='Choose the captured card account and enter days from 1 to 28.';return;}creditCardSaving=true;creditCardError='';const payload={accountReferenceId:Number(creditCardForm.accountReferenceId),cardName:creditCardForm.cardName.trim(),issuerName:creditCardForm.issuerName.trim(),statementDay,dueDay};try{const saved=creditCardEditingId===null?await createCreditCard(payload):await updateCreditCard(creditCardEditingId,payload);creditCards=creditCardEditingId===null?[saved,...creditCards]:creditCards.map(card=>card.id===saved.id?saved:card);creditCardStatus='ready';showCreditCardForm=false;await refreshStories();}catch(cause){creditCardError=cause?.message||'Could not save this credit card.';}finally{creditCardSaving=false;}}
  function openIncomeFlow(){incomeError='';salaryForm={salaryVisibility:'RANGE',salaryRange:'FROM_50000_TO_100000',exactMonthlySalary:'',salaryFrequency:'MONTHLY'};showIncomeFlow=true;}
  async function saveSalary(){incomeSaving=true;incomeError='';try{await saveIncomeProfile({...salaryForm,exactMonthlySalary:salaryForm.salaryVisibility==='EXACT'?Number(salaryForm.exactMonthlySalary):null});await loadIncomeOutlook();showIncomeFlow=false;}catch(cause){incomeError=cause?.message||'Could not save this preference.';}finally{incomeSaving=false;}}
  function openLoanForm(loan=null){loanError='';loanEditingId=loan?.id??null;loanForm=loan?{loanName:loan.loanName||'',loanType:loan.loanType||'HOME',lenderName:loan.lenderName||'',originalPrincipal:String(loan.originalPrincipal??''),monthlyEmiAmount:String(loan.monthlyEmiAmount??''),totalTenureMonths:String(loan.totalTenureMonths??''),firstEmiDueDate:localInputDate(loan.firstEmiDueDate),notes:loan.notes||''}:{loanName:'',loanType:'HOME',lenderName:'',originalPrincipal:'',monthlyEmiAmount:'',totalTenureMonths:'',firstEmiDueDate:'',notes:''};showLoanForm=true;}
  async function saveLoan(){const originalPrincipal=Number(loanForm.originalPrincipal),monthlyEmiAmount=Number(loanForm.monthlyEmiAmount),totalTenureMonths=Number(loanForm.totalTenureMonths);if(!loanForm.loanName.trim()||!loanForm.lenderName.trim()||!loanForm.firstEmiDueDate||originalPrincipal<=0||monthlyEmiAmount<=0||!Number.isInteger(totalTenureMonths)||totalTenureMonths<=0){loanError='Complete every required loan detail with valid positive amounts.';return;}const payload={loanName:loanForm.loanName.trim(),loanType:loanForm.loanType,lenderName:loanForm.lenderName.trim(),originalPrincipal,monthlyEmiAmount,totalTenureMonths,firstEmiDueDate:loanForm.firstEmiDueDate,notes:loanForm.notes};loanSaving=true;loanError='';try{const saved=loanEditingId==null?await createLoan(payload):await updateLoan(loanEditingId,payload);loans=loanEditingId==null?[...loans,saved]:loans.map(loan=>loan.id===saved.id?saved:loan);showLoanForm=false;loanStatus='ready';await refreshStories();}catch(cause){loanError=cause?.message||'Could not save this loan.';}finally{loanSaving=false;}}
  function openMutualFundForm(){fundError='';fundSaved=false;schemeQuery='';selectedScheme=null;showSchemeMenu=false;fundForm={sipAmount:'25000',sipDate:'5',startMonth:'2026-10',paymentMethod:'AUTOPAY',hasHolding:'YES',currentUnits:'128.456',totalInvested:'10000'};showMutualFundForm=true;}
  async function searchSchemes(value){schemeQuery=value;selectedScheme=null;showSchemeMenu=true;fundError='';if(value.trim().length<2){schemeResults=[];schemeSearchStatus='idle';return;}const requestId=++schemeSearchRequest;schemeSearchStatus='loading';try{const result=await searchMutualFunds(value.trim());if(requestId!==schemeSearchRequest)return;schemeResults=Array.isArray(result)?result:result.schemes||[];schemeSearchStatus='ready';}catch(cause){if(requestId!==schemeSearchRequest)return;schemeResults=[];schemeSearchStatus='error';fundError=cause?.message||'Could not search the scheme master.';}}
  function selectScheme(scheme){selectedScheme=scheme;schemeQuery=scheme.schemeName;showSchemeMenu=false;fundError='';}
  async function saveMutualFund(){const sipAmount=Number(fundForm.sipAmount),units=Number(fundForm.currentUnits),invested=Number(fundForm.totalInvested);if(!selectedScheme){fundError='Choose a scheme from the verified scheme master.';return;}if(sipAmount<=0||!fundForm.sipDate||!fundForm.startMonth){fundError='Add a valid monthly amount, SIP date, and start month.';return;}if(fundForm.hasHolding==='YES'&&(!(units>0)||!(invested>0))){fundError='Enter current units and invested amount greater than zero.';return;}const payload={schemeCode:selectedScheme.schemeCode,schemeName:selectedScheme.schemeName,monthlySipAmount:sipAmount,sipDay:Number(fundForm.sipDate),startMonth:fundForm.startMonth,...(selectedScheme.isin?{isin:selectedScheme.isin}:{}),...(fundForm.hasHolding==='YES'?{existingHolding:{currentUnits:units,totalInvestedAmount:invested}}:{})};fundSaving=true;fundError='';try{await createMutualFund(payload);fundSaved=true;await loadMutualFunds();await refreshStories();}catch(cause){fundError=cause?.message||'Could not create this mutual fund.';}finally{fundSaving=false;}}
  function openStockForm(){stockError='';stockQuery='';selectedStock=null;stockResults=[];stockForm={quantity:'',totalInvested:''};showStockForm=true;}
  async function findStocks(value){stockQuery=value;selectedStock=null;stockError='';if(value.trim().length<2){stockResults=[];stockSearchStatus='idle';return;}const requestId=++stockSearchRequest;stockSearchStatus='loading';try{const result=await searchStocks(value.trim());if(requestId!==stockSearchRequest)return;stockResults=Array.isArray(result)?result:[];stockSearchStatus='ready';}catch(cause){if(requestId!==stockSearchRequest)return;stockResults=[];stockSearchStatus='error';stockError=cause?.message||'Could not search stock symbols.';}}
  function selectStock(stock){selectedStock=stock;stockQuery=`${stock.name} (${stock.symbol})`;stockResults=[];stockError='';}
  async function saveStock(){const quantity=Number(stockForm.quantity),totalInvestedAmount=Number(stockForm.totalInvested);if(!selectedStock){stockError='Choose a stock from the search results.';return;}if(!(quantity>0)||!(totalInvestedAmount>0)){stockError='Enter valid positive quantity and total invested amount.';return;}stockSaving=true;stockError='';try{await createStock({symbol:selectedStock.symbol,name:selectedStock.name,exchange:selectedStock.exchange,quantity,totalInvestedAmount});showStockForm=false;await loadStocks();}catch(cause){stockError=cause?.message||'Could not add this stock.';}finally{stockSaving=false;}}
  function openSipConfirmation(fund,occurrence){confirmingSip={fund,occurrence};sipConfirmError='';sipConfirmForm={amount:String(occurrence.amount||fund.monthlySipAmount||''),transactionDate:occurrence.transactionDate||new Date().toISOString().slice(0,10),nav:occurrence.nav==null?'':String(occurrence.nav)};}
  async function saveSipConfirmation(){const amount=Number(sipConfirmForm.amount),nav=Number(sipConfirmForm.nav);if(!(amount>0)||!sipConfirmForm.transactionDate||!(nav>0)){sipConfirmError='Enter a valid amount, transaction date, and NAV.';return;}sipConfirmSaving=true;sipConfirmError='';try{const payload={amount,transactionDate:sipConfirmForm.transactionDate,nav,calculationSource:'NAV_ESTIMATED'};if(confirmingSip.occurrence.status==='CONFIRMED')await updateSipOccurrence(confirmingSip.fund.id,confirmingSip.occurrence.scheduledMonth,payload);else await confirmSipOccurrence(confirmingSip.fund.id,confirmingSip.occurrence.scheduledMonth,payload);confirmingSip=null;await loadMutualFunds();await refreshStories();}catch(cause){sipConfirmError=cause?.message||'Could not save this SIP allocation.';}finally{sipConfirmSaving=false;}}
  async function openFundDetail(id){fundDetail={id};fundDetailStatus='loading';fundDetailError='';try{fundDetail=await getMutualFund(id);fundDetailStatus='ready';}catch(cause){fundDetailStatus='error';fundDetailError=cause?.message||'Could not load this fund.';}}
  function navigate(next){view=next;if(next!=='transactions'){selectedDay=null;activityTab='recent';}window.scrollTo({top:0,behavior:'smooth'});}
  function currentLocalMonth(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;}
  function changeMonth(offset){const[y,m]=selectedMonth.split('-').map(Number),next=new Date(Date.UTC(y,m-1+offset,1)).toISOString().slice(0,7);if(next<=currentLocalMonth()){selectedDay=null;dayItems=[];activityTab='recent';onMonthChange(next);}}
  function buildCalendar(monthValue,apiDays){const[y,m]=monthValue.split('-').map(Number),count=new Date(y,m,0).getDate(),leading=(new Date(y,m-1,1).getDay()+6)%7,values=new Map(apiDays.map(x=>[Number(String(x.date).slice(-2)),x])),today=new Date(),current=today.getFullYear()===y&&today.getMonth()+1===m;return{leading,days:Array.from({length:count},(_,i)=>{const day=i+1,v=values.get(day)||{};return{day,totalSpend:Number(v.totalSpend||0),transactionCount:Number(v.transactionCount||0),intensity:Math.max(0,Math.min(4,Number(v.intensity||0))),future:current&&day>today.getDate()};})};}
  async function selectDate(day){if(!day||day.future)return;selectedDay=day.day;activityTab='day';showAll=false;expandedId=null;await loadDay();}
  async function loadDay(){if(selectedDay==null)return;dayStatus='loading';try{const page=await getExpensesForDate(selectedMonth,isoDate(selectedDay),50);dayItems=page.items||page.expenses||[];dayStatus='ready';}catch{dayStatus='error';}}
  async function openStory(story){openedStory=story;storySlide=0;showStoryEvidence=false;const hasReview=(story.cards||[]).some(card=>(card.actions||[]).some(action=>action.type==='OPEN_COMMITMENT_REVIEW'));if(hasReview){commitmentReviewStatus='loading';showCommitmentReview=true;try{const result=await getCommitmentReview(selectedMonth);commitmentReview=result.items||[];commitmentReviewStatus='ready';}catch(cause){commitmentReviewStatus='error';commitmentError=cause?.message||'Could not load payments needing review.';}}}
  async function resolveCandidate(transactionId,commitmentId){resolvingCandidate=transactionId;try{await resolveCommitmentReview(transactionId,commitmentId);commitmentReview=commitmentReview.filter(item=>item.transactionId!==transactionId);await refreshStories();if(!commitmentReview.length)showCommitmentReview=false;}catch(cause){commitmentError=cause?.message||'Could not save this review.';}finally{resolvingCandidate=null;}}
  function endStorySwipe(event,length){if(storyTouchStart===null)return;const distance=event.changedTouches[0].clientX-storyTouchStart;if(Math.abs(distance)>45)storySlide=Math.max(0,Math.min(length-1,storySlide+(distance<0?1:-1)));storyTouchStart=null;}
  function endRailSwipe(event,length,rail){if(storyRailTouchStart===null)return;const distance=event.changedTouches[0].clientX-storyRailTouchStart;if(Math.abs(distance)>45){const next=Math.max(0,Math.min(length-1,(rail==='home'?homeStoryIndex:storiesRailIndex)+(distance<0?1:-1)));if(rail==='home')homeStoryIndex=next;else storiesRailIndex=next;}storyRailTouchStart=null;}
  async function startEdit(item){editing=item;editAmount=String(item.amount??'');editDate=localInputDate(transactionDate(item));editCategory=category(item)==='Uncategorised'?'':category(item);editSubcategory=item.subcategory?.name||item.subcategory||'';editMerchantId=String(item.merchantId??item.merchant?.id??'');editAccountId=String(item.accountId??item.account?.id??item.sourceAccountId??'');actionError='';optionsError='';if(optionsStatus==='ready'){selectCurrentReferences(item);return;}optionsStatus='loading';try{const result=await getExpenseOptions();editOptions={categories:result.categories||[],merchants:result.merchants||[],accounts:result.accounts||[]};optionsStatus='ready';selectCurrentReferences(item);}catch(cause){optionsStatus='error';optionsError=cause?.message||'Could not load expense options.';}}
  function selectCurrentReferences(item){if(!editMerchantId){const match=editOptions.merchants.find(option=>option.name?.toLowerCase()===merchant(item).toLowerCase());if(match)editMerchantId=String(match.id);}if(!editAccountId){const current=String(item.account?.name??item.sourceAccount?.name??item.accountName??'').toLowerCase(),match=editOptions.accounts.find(option=>option.name?.toLowerCase()===current);if(match)editAccountId=String(match.id);}}
  function changeEditCategory(event){editCategory=event.currentTarget.value;if(!editSubcategories.includes(editSubcategory))editSubcategory='';}
  async function saveEdit(){const amount=Number(editAmount),merchantId=Number(editMerchantId),accountId=Number(editAccountId);if(!editing||saving||optionsStatus!=='ready'||!Number.isFinite(amount)||amount<=0||!editDate||!editCategory||!editSubcategory||!Number.isFinite(merchantId)||!Number.isFinite(accountId))return;saving=true;actionError='';try{await updateExpense(editing.id,{amount,transactionDate:editDate,category:editCategory,subcategory:editSubcategory,merchantId,accountId});editing=null;await Promise.all([loadDay(),refreshRecent(),refreshCalendar(),refreshStories()]);}catch(cause){actionError=cause?.message||'Could not update the transaction.';}finally{saving=false;}}
  async function confirmDelete(){if(!deleting)return;try{await deleteExpense(deleting.id);deleting=null;await Promise.all([loadDay(),refreshRecent(),refreshCalendar(),refreshStories()]);}catch(cause){actionError=cause?.message||'Could not delete the transaction.';deleting=null;}}
  async function addMissingDate(){if(!selected||addingContext)return;addingContext=true;try{const result=await createMissingDateContext(isoDate(selected.day),data.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone);handoff={...result,date:isoDate(selected.day)};}catch(cause){actionError=cause instanceof ApiError?cause.message:'Could not prepare WhatsApp recording.';}finally{addingContext=false;}}
  async function signOut(){loggingOut=true;try{await logout();try{localStorage.removeItem(`${MONEY_MODULES_CACHE_KEY}.real`);localStorage.removeItem(`${MONEY_MODULES_CACHE_KEY}.demo`);}catch{}onLogout();}catch{loggingOut=false;signOutError='Could not sign out.';}}
  async function switchDemoMode(){if(demoSwitching)return;demoSwitching=true;demoError='';try{await onDemoModeChange(!demoMode);loans=[];mutualFunds=[];stocks=[];actions=[];loanStatus='idle';mutualFundStatus='idle';stockStatus='idle';actionsStatus='idle';fundDetail=null;dayItems=[];selectedDay=null;editOptions={categories:[],merchants:[],accounts:[]};optionsStatus='idle';showMoney=false;await loadActions();}catch(cause){demoError=cause?.message||'Could not switch profiles.';}finally{demoSwitching=false;}}
  onMount(()=>{try{commitmentStyle=localStorage.getItem('money-stories.commitment-style')||'playful';}catch{}loadActions();});
</script>

<AppHeader {connectionStatus} {connectionLabel} onRetry={onRetryConnection} onHome={() => navigate('home')} onProfile={() => navigate('you')} />
<main class="app-shell">
{#if connectionStatus==='offline'}<section class="offline-notice"><span>◌</span><div><strong>{cacheUpdatedAt?'Showing your last saved view':'You’re offline'}</strong><p>{cacheUpdatedAt?'We’ll refresh automatically when the service is back.':'Your layout is ready. Connect once to load your expenses and stories.'}</p></div><button on:click={onRetryConnection}>Retry</button></section>{/if}
{#if view==='home'}
  <section class="app-heading"><div><p class="micro-label">{monthLabel(selectedMonth).toUpperCase()}</p><h1>{greeting()}</h1><p>Here’s how your month is unfolding.</p></div></section>
  <SectionState section={calendarSection} title="Spending overview" retry={refreshCalendar}><button class="spending-hero" on:click={()=>navigate('transactions')}><span>MONTHLY SPENDING</span><strong>{money(data.totalSpend)} <small>spent</small></strong><b>{data.transactionCount||0} transactions · View transactions →</b></button></SectionState>
  <section class="home-section"><div class="section-title"><div><p class="micro-label">YOUR STORIES</p><h2>Small signals, clearly told</h2></div><button class="text-link" on:click={()=>navigate('stories')}>See all</button></div><SectionState section={storiesSection} title="Your stories" retry={refreshStories}>{#if homeStories.length}<div class="story-carousel" aria-label="Your stories"><div class="story-dots" aria-label="Choose a story">{#each homeStories as story,index}<button class:active={index===homeStoryIndex} aria-label={`Show story ${index+1} of ${homeStories.length}: ${storyCardFace(story).heading}`} aria-current={index===homeStoryIndex?'true':undefined} on:click={()=>homeStoryIndex=index}></button>{/each}<span>{homeStoryIndex+1} / {homeStories.length}</span></div><div class="story-carousel-viewport" on:touchstart={event=>(storyRailTouchStart=event.touches[0].clientX)} on:touchend={event=>endRailSwipe(event,homeStories.length,'home')}><div class="story-carousel-track" style={`transform:translateX(calc(${homeStoryIndex} * -92%))`}>{#each homeStories as story,index}<button class={`story-carousel-card ${storyTone(story)}`} class:current={index===homeStoryIndex} on:click={()=>openStory(story)}><span class="story-source">{storySource(story)}</span><strong>{storyCardFace(story).heading}</strong><b>{storyCardFace(story).displayValue}</b><i>›</i></button>{/each}</div></div></div>{:else}<div class="story-rail-empty">Your stories will appear here as you add expenses.</div>{/if}</SectionState></section>
  {#if actionsStatus==='loading'}<section class="home-section action-queue-loading">Loading actions…</section>{:else if actionsStatus==='error'}<section class="home-section"><div class="section-error"><p>{actionsError}</p><button on:click={loadActions}>Try again</button></div></section>{:else if visibleActions.length}<section class="home-section action-queue"><div class="section-title"><div><p class="micro-label">NEEDS YOUR ATTENTION</p><h2>Needs your attention</h2></div></div>{#if actionsError}<div class="section-error"><p>{actionsError}</p><button on:click={loadActions}>Try again</button></div>{/if}<div class="action-card-list">{#each visibleActions as item}<article class="action-card"><span class="action-icon">!</span><div><strong>{item.presentation.title}</strong><p>{item.presentation.description}</p><button class="primary action-complete" disabled={completingActionId!==null} on:click={()=>completeOpenAction(item.action)}>{completingActionId===item.action.id?'Marking loan closed…':item.presentation.cta}</button></div></article>{/each}</div></section>{/if}
  <section class="home-section"><div class="section-title"><div><p class="micro-label">RECENT ACTIVITY</p><h2>Your latest expenses</h2></div><button class="text-link" on:click={()=>navigate('transactions')}>See all</button></div><div class="compact-list">{#each recentItems.slice(0,3) as item}<button class="row-main" on:click={()=>{navigate('transactions');startEdit(item);}}><div><strong>{merchant(item)}</strong><span>{category(item)} · {dateLabel(transactionDate(item))}</span></div><b>− {money(item.amount)}</b></button>{:else}<p class="empty-copy">No expenses recorded yet.</p>{/each}</div></section>
  <button class="your-money-card" on:click={openMoney}><span>◒</span><div><strong>Your money</strong><small>See your incoming and outgoing plan, only when you’re ready.</small></div><b>Explore ›</b></button>
{:else if view==='transactions'}
  <section class="workspace-heading"><div><p class="micro-label">EXPENSE WORKSPACE</p><h1>Transactions</h1><p>AI-captured expenses, ready for your review.</p></div><label class="month-switcher"><button type="button" on:click={()=>changeMonth(-1)}>←</button><input type="month" value={selectedMonth} max={currentLocalMonth()} on:change={e=>onMonthChange(e.currentTarget.value)}/><button type="button" on:click={()=>changeMonth(1)}>→</button></label></section>
  <SectionState section={calendarSection} title="Spending calendar" retry={refreshCalendar}><section class="month-card"><div class="month-summary"><div><span>Total recorded</span><strong>{money(data.totalSpend)}</strong></div><div><span>Transactions</span><strong>{data.transactionCount||0}</strong></div><div><span>Highest day</span><strong>{money(data.highestSpend)}</strong></div></div><div class="weekdays">{#each ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as d}<span>{d}</span>{/each}</div><div class="calendar">{#each Array(calendar.leading) as _}<span></span>{/each}{#each calendar.days as d}<button class:future={d.future} class:selected={selectedDay===d.day} class={`level-${d.intensity}`} disabled={d.future} on:click={()=>selectDate(d)}>{d.day}</button>{/each}</div><div class="legend"><span>Lower spend</span><div>{#each [0,1,2,3,4] as l}<i class={`level-${l}`}></i>{/each}</div><span>Higher spend</span></div></section></SectionState>
  <section class="activity-panel adaptive-activity"><div class="activity-tabs"><button class:active={activityTab==='recent'} on:click={()=>activityTab='recent'}>Recent</button><button class:active={activityTab==='day'} on:click={()=>activityTab='day'}>{selected?`${selected.day} selected`:'Select a date'}</button></div>{#if activityTab==='day'&&dayStatus==='loading'}<div class="activity-loading">Loading transactions…</div>{:else if activityTab==='day'&&dayStatus==='error'}<div class="section-error"><p>Could not load this date.</p><button on:click={loadDay}>Try again</button></div>{:else}<div class="activity-summary"><p class="micro-label">{activityTab==='recent'?'RECENT EXPENSES':selected?`${selected.day} ${monthLabel(selectedMonth)}`:'SELECT A DATE'}</p><h2>{activityTab==='recent'?`${recentItems.length} recent transactions`:selected?`${selected.transactionCount} transactions · ${money(selected.totalSpend)}`:'Choose a date in the calendar'}</h2></div><div class="compact-list">{#each visibleItems as item}<article class:expanded={expandedId===item.id} class="compact-row"><button class="row-main" on:click={()=>expandedId=expandedId===item.id?null:item.id}><div><strong>{merchant(item)}</strong><span>{category(item)} · {dateLabel(transactionDate(item))}</span></div><div class="row-value"><b>− {money(item.amount)}</b><span class:open={expandedId===item.id} class="row-chevron">⌄</span></div></button>{#if expandedId===item.id}<div class="row-actions"><button on:click={()=>startEdit(item)}>Edit transaction</button><button class="danger" on:click={()=>deleting=item}>Delete</button></div>{/if}</article>{:else}<p class="empty-copy">No transactions for this view.</p>{/each}</div>{#if activeItems.length>5}<button class="view-all" on:click={()=>showAll=!showAll}>{showAll?'Show fewer ↑':`View all ${activeItems.length} transactions ↓`}</button>{/if}{/if}</section>
  <button class="wide-button" disabled={!selected||addingContext} on:click={addMissingDate}>{addingContext?'Preparing WhatsApp…':selected?'+ Add missing expense':'Select a date to add an expense'}</button><button class="cleanup-card" on:click={()=>showNormalization=true}><span>✦</span><div><strong>Expense cleanup</strong><small>Fix merchant and account names captured by AI.</small></div><b>Open ›</b></button>
{:else if view==='stories'}
  <section class="workspace-heading"><div><p class="micro-label">YOUR MONEY, EXPLAINED</p><h1>Stories</h1><p>Insights across the information you choose to share.</p></div></section><div class="story-filters">{#each ['All','Spending','Investing','Planning'] as filter}<button class:active={storyFilter===filter} on:click={()=>{storyFilter=filter;storiesRailIndex=0;}}>{filter}</button>{/each}</div><div class="commitment-style-control"><span>Commitment style</span><button class:active={commitmentStyle==='calm'} on:click={()=>setCommitmentStyle('calm')}>Calm</button><button class:active={commitmentStyle==='playful'} on:click={()=>setCommitmentStyle('playful')}>Playful ✨</button></div><SectionState section={storiesSection} title="Stories" retry={refreshStories}>{#if filteredStories.length}<div class="story-carousel story-carousel-full" aria-label={`${storyFilter} stories`}><div class="story-dots" aria-label="Choose a story">{#each filteredStories as story,index}<button class:active={index===storiesRailIndex} aria-label={`Show story ${index+1} of ${filteredStories.length}: ${storyCardFace(story).heading}`} aria-current={index===storiesRailIndex?'true':undefined} on:click={()=>storiesRailIndex=index}></button>{/each}<span>{storiesRailIndex+1} / {filteredStories.length}</span></div><div class="story-carousel-viewport" on:touchstart={event=>(storyRailTouchStart=event.touches[0].clientX)} on:touchend={event=>endRailSwipe(event,filteredStories.length,'full')}><div class="story-carousel-track" style={`transform:translateX(calc(${storiesRailIndex} * -92%))`}>{#each filteredStories as story,index}<button class={`story-carousel-card ${storyTone(story)}`} class:commitment-card={isCommitment(story)} class:playful={isCommitment(story)&&commitmentStyle==='playful'} class:current={index===storiesRailIndex} on:click={()=>openStory(story)}><span class="story-source">{storySource(story)}</span>{#if storyIcon(story)}<span class="commitment-icon">{storyIcon(story)}</span>{/if}<strong>{storyHeading(story)}</strong><b>{storyCardFace(story).displayValue}</b><i>›</i></button>{/each}</div></div></div>{:else}<div class="empty-state"><span>✦</span><h2>No {storyFilter.toLowerCase()} stories yet</h2><p>As you choose to add more information, relevant stories will appear here.</p></div>{/if}</SectionState>
{:else}
  <ProfileSettings {demoMode} {demoSwitching} {demoError} {loggingOut} {signOutError} {storyControls} onNavigate={navigate} onOpenMoney={openMoney} onDemoModeChange={switchDemoMode} onSignOut={signOut} />
{/if}
</main>
<BottomNav {view} onNavigate={navigate} />

<!-- svelte-ignore a11y_click_events_have_key_events -->
{#if showMoney}
  <div class="modal-backdrop" on:click={()=>showMoney=false} on:keydown={(event)=>event.key==='Escape'&&(showMoney=false)} role="presentation">
    <section class="modal money-modal" on:click|stopPropagation role="dialog" aria-modal="true" tabindex="-1">
      <button class="close" on:click={()=>showMoney=false}>×</button>
      <p class="micro-label">OPTIONAL, PRIVATE, YOURS</p><h2>Build your complete money picture</h2>
      <p class="module-reassurance">You choose what to add. Nothing is required, and you can remove a module anytime.</p>
      <section class="income-module"><div class="loans-heading"><div><strong>Salary outlook</strong><small>Private estimate — never treated as your account balance</small></div><span class="verified-pill">Optional</span></div>{#if incomeStatus==='loading'}<p>Loading your private outlook…</p>{:else if incomeStatus==='error'}<div class="loan-state error"><span>{incomeError}</span><button on:click={loadIncomeOutlook}>Try again</button></div>{:else if incomeOutlook.salary}<div class="income-summary masked"><span>Salary saved</span><strong>{incomeOutlook.salary.maskedValue}</strong><button class="income-edit" on:click={openIncomeFlow} aria-label="Update salary outlook" title="Update salary outlook">🔧</button><small>Masked before it reaches this screen.</small></div>{:else}<div class="income-summary"><strong>Start with a range</strong><small>Only you decide whether to share a range or an exact amount.</small></div><button class="add-fund-row" on:click={openIncomeFlow}>Set up salary outlook</button>{/if}</section>
      <section class="loans-module"><div class="loans-heading"><div><strong>Monthly commitments</strong><small>Rent, bills, subscriptions and other repeatable obligations</small></div></div>{#if commitmentStatus==='loading'}<p class="loan-state">Loading commitments…</p>{:else if commitmentStatus==='error'}<div class="loan-state error"><span>{commitmentError}</span><button on:click={loadCommitments}>Try again</button></div>{:else if commitments.length}{#each commitments as commitment}<article class="loan-row"><span>↻</span><div><strong>{commitment.label}</strong><small>{commitment.amountMode==='RECENT_BILL_ESTIMATE'?'Recent-bill estimate':'Monthly planning amount'}{commitment.dueDay?` · due around the ${commitment.dueDay}`:''}</small></div><div><b>{money(commitment.planningAmount)}/mo</b><small>{commitment.status.toLowerCase()}</small></div></article>{/each}{:else}<p class="loan-state">No recurring commitments yet.</p>{/if}<button class="add-loan-row" on:click={()=>openCommitmentForm()}>＋ Add a monthly commitment</button></section>
      <section class="loans-module"><div class="loans-heading"><div><strong>Credit cards</strong><small>Turn captured card spending into the bill due next month</small></div></div>{#if creditCardStatus==='loading'}<p class="loan-state">Loading credit cards…</p>{:else if creditCardStatus==='error'}<div class="loan-state error"><span>{creditCardError}</span><button on:click={loadCreditCards}>Try again</button></div>{:else if creditCards.length}{#each creditCards as card}<article class="loan-row"><span>▣</span><div><strong class="loan-name">{card.cardName}<button class="loan-edit" on:click={()=>openCreditCardForm(card)} aria-label={`Edit ${card.cardName}`} title="Edit credit card">🔧</button></strong><small>{card.issuerName} · captured as {card.accountName}</small></div><div><b>Due {card.dueDay}</b><small>Statement {card.statementDay}</small></div></article>{/each}{:else}<p class="loan-state">Add a card once it appears as an account in your captured expenses.</p>{/if}<button class="add-loan-row" on:click={()=>openCreditCardForm()}>＋ Add a credit card</button></section>
      {#each [['◒','Emergency fund','Track your safety cushion'],['◎','Goals','Plan for what matters'],['▤','Budgets','Set gentle spending limits']] as module}
        <button class="module-row" on:click={()=>showMoney=false}><span>{module[0]}</span><div><strong>{module[1]}</strong><small>{module[2]}</small></div><b>Coming soon</b></button>
      {/each}
      {#if mutualFunds.some(fund=>fund.currentSip)}<section class="loans-module"><div class="loans-heading"><div><strong>This month's SIPs</strong><small>Confirm or correct allocations here; the story updates automatically.</small></div></div>{#each mutualFunds.filter(fund=>fund.currentSip) as fund}<article class="loan-row"><span>{fund.currentSip.status==='CONFIRMED'?'✓':'◷'}</span><div><strong>{fund.schemeName}</strong><small>{fund.currentSip.status==='CONFIRMED'?`Allocated ${dateLabel(fund.currentSip.transactionDate)} · NAV ${moneyDecimal(fund.currentSip.nav)}`:`${money(fund.currentSip.amount)} ready to confirm`}</small></div><button class="secondary" on:click={()=>openSipConfirmation(fund,fund.currentSip)}>{fund.currentSip.status==='CONFIRMED'?'Edit allocation':'Confirm allocation'}</button></article>{/each}</section>{/if}
      <section class="mutual-funds-module"><div class="loans-heading"><div><strong>Mutual funds</strong><small>Portfolio value from the latest available NAV</small></div><span class="verified-pill">Scheme API</span></div>{#if mutualFundStatus==='loading'}<p>Loading your funds…</p>{:else if mutualFundStatus==='error'}<div class="loan-state error"><span>{mutualFundError}</span><button on:click={loadMutualFunds}>Try again</button></div>{:else if mutualFunds.length}<section class="portfolio-total"><span>Total portfolio value</span>{#if mutualPortfolio.current!==null}<strong>{money(mutualPortfolio.current)}</strong><small class:positive={mutualPortfolio.pnl>=0} class:negative={mutualPortfolio.pnl<0}>{mutualPortfolio.pnl>=0?'+':''}{money(mutualPortfolio.pnl)} overall P&amp;L</small>{:else}<strong>{money(mutualPortfolio.invested)}</strong><small>Current valuation is temporarily unavailable</small>{/if}</section><div class="fund-card-list">{#each mutualFunds as fund}<button class={`fund-card ${fundAccent(fund.id)}`} on:click={()=>openFundDetail(fund.id)} aria-label={`Open ${fund.schemeName} details`}><span class="fund-card-orb"></span><div class="fund-card-title"><strong>{fund.schemeName}</strong><small>{fundSubtitle(fund.schemeName)}</small></div>{#if fund.currentValue!==null}<div class="fund-card-values"><div class:positive={Number(fund.profitOrLoss)>=0} class:negative={Number(fund.profitOrLoss)<0}><span>P&amp;L</span><b>{Number(fund.profitOrLoss)>=0?'+':''}{compactMoney(fund.profitOrLoss)}</b><small>{Number(fund.profitOrLossPercent)>=0?'+':''}{Number(fund.profitOrLossPercent).toFixed(2)}%</small></div><div><span>Invested</span><b>{compactMoney(fund.invested)}</b></div><div><span>Current</span><b>{compactMoney(fund.currentValue)}</b></div></div><p class="fund-card-nav">Latest NAV {moneyDecimal(fund.latestNav)}</p>{:else}<p class="fund-valuation-unavailable">Current valuation is temporarily unavailable. Your invested amount is {money(fund.invested)}.</p>{/if}<footer>{fund.activeSip?`1 SIP · ${compactMoney(fund.activeSip.amount)} on the ${fund.activeSip.day}${fund.activeSip.day===1?'st':fund.activeSip.day===2?'nd':fund.activeSip.day===3?'rd':'th'} of every month`:'No active SIP'}<span>View details →</span></footer></button>{/each}</div>{:else}<p>Choose one verified scheme, then add only the details needed for your SIP.</p>{/if}<button class="add-fund-row" on:click={openMutualFundForm}>＋ Add a mutual fund</button></section>
      <section class="mutual-funds-module stocks-module"><div class="loans-heading"><div><strong>Stocks</strong><small>Portfolio value from the latest available market price</small></div><span class="verified-pill">Market data</span></div>{#if stockStatus==='loading'}<p>Loading your stocks…</p>{:else if stockStatus==='error'}<div class="loan-state error"><span>{stockError}</span><button on:click={loadStocks}>Try again</button></div>{:else if stocks.length}<section class="portfolio-total"><span>Total stock value</span>{#if stockPortfolio.current!==null}<strong>{money(stockPortfolio.current)}</strong><small class:positive={stockPortfolio.pnl>=0} class:negative={stockPortfolio.pnl<0}>{stockPortfolio.pnl>=0?'+':''}{money(stockPortfolio.pnl)} overall P&amp;L</small>{:else}<strong>{money(stockPortfolio.invested)}</strong><small>Current valuation is temporarily unavailable</small>{/if}</section><div class="fund-card-list">{#each stocks as stock}<article class={`fund-card ${fundAccent(stock.id)}`}><span class="fund-card-orb"></span><div class="fund-card-title"><strong>{stock.name}</strong><small>{stock.symbol}{stock.exchange?` · ${stock.exchange}`:''}</small></div>{#if stock.currentValue!==null}<div class="fund-card-values"><div class:positive={Number(stock.profitOrLoss)>=0} class:negative={Number(stock.profitOrLoss)<0}><span>P&amp;L</span><b>{Number(stock.profitOrLoss)>=0?'+':''}{compactMoney(stock.profitOrLoss)}</b><small>{Number(stock.profitOrLossPercent)>=0?'+':''}{Number(stock.profitOrLossPercent).toFixed(2)}%</small></div><div><span>Invested</span><b>{compactMoney(stock.invested)}</b></div><div><span>Current</span><b>{compactMoney(stock.currentValue)}</b></div></div><p class="fund-card-nav">Latest price {moneyDecimal(stock.latestPrice)} · {Number(stock.quantity).toFixed(3)} shares</p>{:else}<p class="fund-valuation-unavailable">Current price is temporarily unavailable. Your invested amount is {money(stock.invested)}.</p>{/if}</article>{/each}</div>{:else}<p>Search a listed stock, then add the shares and amount you already invested.</p>{/if}<button class="add-fund-row" on:click={openStockForm}>＋ Add a stock</button></section>
      <section class="loans-module"><div class="loans-heading"><div><strong>Loans</strong><small>Track repayments and monthly commitments</small></div>{#if loans.length}<div class="loan-total"><span>Total monthly EMI</span><b>{money(totalMonthlyEmi)}/mo</b></div>{/if}</div>
        {#if loanStatus==='loading'}<p class="loan-state">Loading your loans…</p>{:else if loanStatus==='error'}<div class="loan-state error"><span>{loanError}</span><button on:click={loadLoans}>Try again</button></div>{:else if loans.length}{#each loans as loan}{@const schedule=loanSchedule(loan)}<article class="loan-row"><span>₹</span><div><strong class="loan-name">{loan.loanName}<button class="loan-edit" on:click={()=>openLoanForm(loan)} aria-label={`Edit ${loan.loanName}`} title="Edit loan">🔧</button></strong><small>{loan.lenderName} · {loan.loanType.replaceAll('_',' ')} · {loan.totalTenureMonths} months</small></div><div><b>{money(loan.monthlyEmiAmount)}/mo</b><small>{money(loan.originalPrincipal)} principal</small></div>{#if schedule}<div class="loan-progress" aria-label={`${schedule.due} of ${schedule.tenure} EMIs due till ${schedule.endLabel}`}><div><span>{schedule.due} of {schedule.tenure} EMIs due till {schedule.endLabel}</span></div><i style={`--loan-progress:${schedule.percent}%`}></i></div>{/if}</article>{/each}{:else}<p class="loan-state">No loans added yet.</p>{/if}
        <button class="add-loan-row" on:click={()=>openLoanForm()}>＋ Add another loan</button>
      </section>
      <p class="module-footnote">These modules use normal forms—not AI cleanup—and only inform stories if you turn that on.</p>
    </section>
  </div>
{/if}
{#if showCommitmentForm}<div class="modal-backdrop"><section class="modal loan-form" role="dialog" aria-modal="true"><button class="close" on:click={()=>showCommitmentForm=false}>×</button><p class="micro-label">MONTHLY COMMITMENT</p><h2>Add a repeatable obligation</h2><p class="module-reassurance">This is a planning estimate, not proof that a bill was paid.</p><label>Name<input bind:value={commitmentForm.label} placeholder="e.g. Home rent" maxlength="120"/></label><label>Monthly planning amount<input type="number" inputmode="decimal" min="0.01" bind:value={commitmentForm.planningAmount}/></label><label>Expected day <span class="optional">Optional</span><input type="number" min="1" max="28" bind:value={commitmentForm.dueDay}/></label><label>Amount basis<select bind:value={commitmentForm.amountMode}><option value="FIXED">Fixed amount</option><option value="USER_ESTIMATE">My estimate</option></select></label>{#if commitmentError}<p class="form-error">{commitmentError}</p>{/if}<div class="modal-actions"><button class="secondary" on:click={()=>showCommitmentForm=false}>Cancel</button><button class="primary" on:click={saveCommitment} disabled={commitmentSaving}>{commitmentSaving?'Saving…':'Add commitment'}</button></div></section></div>{/if}
{#if showCreditCardForm}<div class="modal-backdrop"><section class="modal loan-form" role="dialog" aria-modal="true"><button class="close" on:click={()=>showCreditCardForm=false}>×</button><p class="micro-label">CREDIT-CARD BILLING</p><h2>{creditCardEditingId===null?'Add a credit card':'Edit credit card'}</h2><p class="module-reassurance">We add only expenses captured against this account between statement dates to the bill due in that month.</p><label>Captured account<select bind:value={creditCardForm.accountReferenceId}><option value="" disabled>Select the card account</option>{#each editOptions.accounts as account}<option value={String(account.id)}>{account.name}</option>{/each}</select></label><label>Card name<input bind:value={creditCardForm.cardName} placeholder="e.g. Millennia" maxlength="120"/></label><label>Issuer / vendor<input bind:value={creditCardForm.issuerName} placeholder="e.g. HDFC Bank" maxlength="120"/></label><label>Bill generation day<input type="number" min="1" max="28" bind:value={creditCardForm.statementDay}/></label><label>Payment due day<input type="number" min="1" max="28" bind:value={creditCardForm.dueDay}/></label>{#if creditCardError}<p class="form-error">{creditCardError}</p>{/if}<div class="modal-actions"><button class="secondary" on:click={()=>showCreditCardForm=false}>Cancel</button><button class="primary" on:click={saveCreditCard} disabled={creditCardSaving||optionsStatus!=='ready'}>{creditCardSaving?'Saving…':creditCardEditingId===null?'Add credit card':'Save changes'}</button></div></section></div>{/if}
{#if showIncomeFlow}<div class="modal-backdrop income-flow-backdrop"><section class="modal income-flow" role="dialog" aria-modal="true"><button class="close" on:click={()=>showIncomeFlow=false}>×</button><p class="micro-label">PRIVATE SALARY CONTEXT</p><h2>What range feels comfortable to share?</h2><p class="module-reassurance">A range is enough. This is not a request for a payslip, and it never changes your balance.</p><div class="range-options">{#each ['UNDER_25000','FROM_25000_TO_50000','FROM_50000_TO_100000','FROM_100000_TO_200000','OVER_200000'] as range}<button class:active={salaryForm.salaryRange===range&&salaryForm.salaryVisibility==='RANGE'} on:click={()=>{salaryForm.salaryVisibility='RANGE';salaryForm.salaryRange=range;}}>{incomeRangeLabel(range)}</button>{/each}</div><button class="text-link income-exact-toggle" on:click={()=>salaryForm.salaryVisibility=salaryForm.salaryVisibility==='EXACT'?'RANGE':'EXACT'}>{salaryForm.salaryVisibility==='EXACT'?'Use a range instead':'I’m comfortable sharing the exact amount'}</button>{#if salaryForm.salaryVisibility==='EXACT'}<label>Monthly take-home salary<input type="number" min="1" inputmode="decimal" bind:value={salaryForm.exactMonthlySalary} placeholder="Optional exact amount"/></label>{/if}<label>How often does it arrive?<select bind:value={salaryForm.salaryFrequency}>{#each ['MONTHLY','TWICE_MONTHLY','WEEKLY','IRREGULAR'] as frequency}<option value={frequency}>{frequency.replaceAll('_',' ').toLowerCase()}</option>{/each}</select></label>{#if incomeError}<p class="form-error">{incomeError}</p>{/if}<div class="modal-actions"><button class="secondary" on:click={()=>{salaryForm.salaryVisibility='SKIPPED';saveSalary();}} disabled={incomeSaving}>Skip for now</button><button class="primary" on:click={saveSalary} disabled={incomeSaving}>{incomeSaving?'Saving…':'Save salary outlook'}</button></div></section></div>{/if}
{#if showLoanForm}
  <div class="modal-backdrop loan-form-backdrop" role="presentation"><section class="modal loan-form" role="dialog" aria-modal="true" tabindex="-1"><button class="close" on:click={()=>showLoanForm=false}>×</button><p class="micro-label">LOAN DETAILS</p><h2>{loanEditingId==null?'Add a loan':'Edit loan'}</h2><p class="module-reassurance">Your loan information is stored securely in your account.</p><label>Loan name<input bind:value={loanForm.loanName} placeholder="e.g. HDFC Home Loan" maxlength="255" /></label><label>Loan type<select bind:value={loanForm.loanType}>{#each ['HOME','VEHICLE','PERSONAL','EDUCATION','CREDIT_CARD_EMI','OTHER'] as type}<option value={type}>{type.replaceAll('_',' ')}</option>{/each}</select></label><label>Original loan principal<input type="number" inputmode="decimal" min="1" bind:value={loanForm.originalPrincipal} placeholder="e.g. 4200000" /></label><label>Monthly EMI amount<input type="number" inputmode="decimal" min="1" bind:value={loanForm.monthlyEmiAmount} placeholder="e.g. 38600" /></label><label>Total tenure in months<input type="number" inputmode="numeric" min="1" bind:value={loanForm.totalTenureMonths} placeholder="e.g. 240" /></label><label>First EMI due date<input type="date" bind:value={loanForm.firstEmiDueDate} /></label><label>Bank / lender<input bind:value={loanForm.lenderName} placeholder="e.g. HDFC Bank" maxlength="255" /></label><label>Notes <span class="optional">Optional</span><input bind:value={loanForm.notes} placeholder="e.g. Primary residence" /></label>{#if loanError}<p class="form-error">{loanError}</p>{/if}<div class="modal-actions"><button class="secondary" on:click={()=>showLoanForm=false}>Cancel</button><button class="primary" on:click={saveLoan} disabled={loanSaving}>{loanSaving?'Saving…':loanEditingId==null?'Add loan':'Save changes'}</button></div></section></div>
{/if}
{#if showMutualFundForm}
  <div class="modal-backdrop fund-form-backdrop" role="presentation"><section class="modal fund-form" role="dialog" aria-modal="true" tabindex="-1"><button class="close" on:click={()=>showMutualFundForm=false}>×</button>
    {#if fundSaved}<div class="fund-success"><span>✓</span><p class="micro-label">SIP READY</p><h2>Your SIP is set up</h2><p>{money(fundForm.sipAmount)} will be tracked monthly for {selectedScheme.schemeName}. The first occurrence will be due in {monthLabel(fundForm.startMonth)}.</p><button class="primary" on:click={()=>showMutualFundForm=false}>Done</button></div>
    {:else}<p class="micro-label">MUTUAL FUND · MONTHLY SIP</p><h2>Add a mutual fund</h2><p class="module-reassurance">Search the official scheme master. A returned name is one verified fund, plan and option.</p>
      <div class="fund-section"><span class="fund-section-label">1 · FUND</span><label class="scheme-picker">Search and select scheme<input value={schemeQuery} on:focus={()=>showSchemeMenu=true} on:input={e=>searchSchemes(e.currentTarget.value)} placeholder="Type at least 2 characters" autocomplete="off" />{#if showSchemeMenu}<div class="scheme-menu">{#if schemeSearchStatus==='loading'}<p>Searching schemes…</p>{:else if schemeQuery.trim().length<2}<p>Type at least 2 characters to search.</p>{:else}{#each schemeResults as scheme}<button type="button" on:mousedown|preventDefault={()=>selectScheme(scheme)}><strong>{scheme.schemeName}</strong><small>Scheme code {scheme.schemeCode} · {scheme.latestNav==null?'Latest NAV unavailable':`Latest NAV ${moneyDecimal(scheme.latestNav)}`}</small></button>{:else}<p>No matching scheme found.</p>{/each}{/if}</div>{/if}</label>{#if selectedScheme}<div class="scheme-validated"><span>✓</span><div><strong>Verified by scheme master</strong><small>Code {selectedScheme.schemeCode} · {selectedScheme.latestNav==null?'Latest NAV unavailable':`Latest NAV ${moneyDecimal(selectedScheme.latestNav)}`}</small></div></div>{/if}</div>
      <div class="fund-section"><span class="fund-section-label">2 · SIP</span><label>Monthly SIP amount<input type="number" inputmode="decimal" min="1" bind:value={fundForm.sipAmount} /></label><div class="fund-field-pair"><label>SIP date<select bind:value={fundForm.sipDate}>{#each Array(28) as _,index}<option value={index+1}>{index+1}{index===0?'st':index===1?'nd':index===2?'rd':'th'} of every month</option>{/each}</select></label><label>Start month<input type="month" bind:value={fundForm.startMonth} /></label></div></div>
      <div class="fund-section"><span class="fund-section-label">3 · EXISTING HOLDING <em>OPTIONAL</em></span><fieldset><legend>Do you already hold this fund?</legend><label class="choice"><input type="radio" bind:group={fundForm.hasHolding} value="NO" /> No</label><label class="choice"><input type="radio" bind:group={fundForm.hasHolding} value="YES" /> Yes</label></fieldset>{#if fundForm.hasHolding==='YES'}<div class="fund-field-pair"><label>Current units<input type="number" inputmode="decimal" min="0.001" step="0.001" bind:value={fundForm.currentUnits} /></label><label>Total amount invested<input type="number" inputmode="decimal" min="0.01" bind:value={fundForm.totalInvested} /></label></div><p class="fund-disclaimer">Average purchase cost is calculated by the backend after the opening balance is recorded.</p>{/if}</div>
      {#if fundError}<p class="form-error">{fundError}</p>{/if}<div class="modal-actions"><button class="secondary" on:click={()=>showMutualFundForm=false}>Cancel</button><button class="primary" on:click={saveMutualFund} disabled={fundSaving}>{fundSaving?'Creating…':'Create SIP plan'}</button></div>
    {/if}</section></div>
{/if}
{#if showStockForm}
  <div class="modal-backdrop fund-form-backdrop" role="presentation"><section class="modal fund-form" role="dialog" aria-modal="true" tabindex="-1"><button class="close" on:click={()=>showStockForm=false}>×</button><p class="micro-label">STOCK HOLDING</p><h2>Add a stock</h2><p class="module-reassurance">Search market symbols, then record the shares and total amount you already invested. Editing and selling will follow in a later update.</p><div class="fund-section"><span class="fund-section-label">1 · STOCK</span><label class="scheme-picker">Search and select stock<input value={stockQuery} on:input={e=>findStocks(e.currentTarget.value)} placeholder="Type at least 2 characters" autocomplete="off" />{#if stockQuery.trim().length>=2&&!selectedStock}<div class="scheme-menu">{#if stockSearchStatus==='loading'}<p>Searching stock symbols…</p>{:else if stockSearchStatus==='error'}<p>Could not search stocks.</p>{:else}{#each stockResults as stock}<button type="button" on:mousedown|preventDefault={()=>selectStock(stock)}><strong>{stock.name||stock.symbol}</strong><small>{stock.symbol}{stock.exchange?` · ${stock.exchange}`:''} · {stock.latestPrice==null?'Latest price unavailable':`Latest price ${moneyDecimal(stock.latestPrice)}`}</small></button>{:else}<p>No matching listed stock found.</p>{/each}{/if}</div>{/if}</label>{#if selectedStock}<div class="scheme-validated"><span>✓</span><div><strong>Verified market symbol</strong><small>{selectedStock.symbol}{selectedStock.exchange?` · ${selectedStock.exchange}`:''} · {selectedStock.latestPrice==null?'Latest price unavailable':`Latest price ${moneyDecimal(selectedStock.latestPrice)}`}</small></div></div>{/if}</div><div class="fund-section"><span class="fund-section-label">2 · HOLDING</span><div class="fund-field-pair"><label>Shares held<input type="number" inputmode="decimal" min="0.001" step="0.001" bind:value={stockForm.quantity} /></label><label>Total amount invested<input type="number" inputmode="decimal" min="0.01" bind:value={stockForm.totalInvested} /></label></div></div>{#if stockError}<p class="form-error">{stockError}</p>{/if}<div class="modal-actions"><button class="secondary" on:click={()=>showStockForm=false}>Cancel</button><button class="primary" on:click={saveStock} disabled={stockSaving}>{stockSaving?'Adding…':'Add stock'}</button></div></section></div>
{/if}
<!-- svelte-ignore a11y_click_events_have_key_events -->
{#if fundDetail}<div class="modal-backdrop fund-form-backdrop"><section class="modal fund-detail" role="dialog" aria-modal="true"><button class="close" on:click={()=>fundDetail=null}>×</button>{#if fundDetailStatus==='loading'}<p class="micro-label">FUND DETAILS</p><h2>Loading fund details…</h2>{:else if fundDetailStatus==='error'}<p class="micro-label">FUND DETAILS</p><h2>Couldn’t load this fund</h2><p>{fundDetailError}</p><button class="primary" on:click={()=>openFundDetail(fundDetail.id)}>Try again</button>{:else}<p class="micro-label">FUND DETAILS</p><h2>{fundDetail.schemeName}</h2><div class="detail-value"><span>Current value</span><strong>{money(fundDetail.currentValue)}</strong></div><div class:positive={Number(fundDetail.profitOrLoss)>=0} class:negative={Number(fundDetail.profitOrLoss)<0} class="detail-pnl"><span>Total P&amp;L</span><strong>{Number(fundDetail.profitOrLoss)>=0?'+':''}{money(fundDetail.profitOrLoss)}</strong><b>{Number(fundDetail.profitOrLossPercent)>=0?'+':''}{Number(fundDetail.profitOrLossPercent).toFixed(2)}%</b></div><div class="detail-grid"><div><span>Invested</span><b>{money(fundDetail.invested)}</b></div><div><span>Units</span><b>{Number(fundDetail.units).toFixed(3)}</b></div><div><span>Average NAV</span><b>{moneyDecimal(fundDetail.averageNav)}</b></div><div><span>Current NAV</span><b>{moneyDecimal(fundDetail.currentNav)}</b></div></div><p class="fund-disclaimer">Average NAV is based on confirmed investments. Current NAV is the latest available MFAPI value.</p>{/if}</section></div>{/if}
{#if confirmingSip}<div class="modal-backdrop fund-form-backdrop"><section class="modal fund-form" role="dialog" aria-modal="true"><button class="close" on:click={()=>confirmingSip=null}>×</button><p class="micro-label">CONFIRM SIP INVESTMENT</p><h2>Was this SIP processed?</h2><p class="module-reassurance">Units will be estimated from the NAV and marked as an estimate until you correct them from your statement.</p><div class="source-note"><strong>{confirmingSip.fund.schemeName}</strong><span>{confirmingSip.occurrence.scheduledMonth} occurrence</span></div><label>Amount invested<input type="number" min="0.01" step="0.01" bind:value={sipConfirmForm.amount}/></label><label>Transaction date<input type="date" bind:value={sipConfirmForm.transactionDate}/></label><label>NAV <span class="optional">Estimated</span><input type="number" min="0.0001" step="0.0001" bind:value={sipConfirmForm.nav} placeholder="e.g. 87.25"/></label>{#if sipConfirmError}<p class="form-error">{sipConfirmError}</p>{/if}<div class="modal-actions"><button class="secondary" on:click={()=>confirmingSip=null}>Cancel</button><button class="primary" on:click={saveSipConfirmation} disabled={sipConfirmSaving}>{sipConfirmSaving?'Confirming…':'Confirm estimate'}</button></div></section></div>{/if}
<!-- svelte-ignore a11y_click_events_have_key_events -->
{#if showNormalization}<div class="account-repair-backdrop" role="presentation" on:click={()=>showNormalization=false} on:keydown={(event)=>event.key==='Escape'&&(showNormalization=false)}><section class="account-repair-dialog" role="dialog" aria-modal="true" tabindex="-1" on:click|stopPropagation><header class="account-repair-bar"><div><span class="repair-symbol">✦</span><span><p>EXPENSE DATA ONLY</p><strong>Expense cleanup</strong></span></div><button on:click={()=>showNormalization=false}>×</button></header><div class="account-repair-content"><Normalization /></div></section></div>{/if}
<!-- svelte-ignore a11y_click_events_have_key_events -->
{#if openedStory}<div class="story-reader-backdrop" role="presentation" on:click={()=>openedStory=null} on:keydown={(event)=>event.key==='Escape'&&(openedStory=null)}><section class="story-detail" role="dialog" aria-modal="true" tabindex="-1" on:click|stopPropagation><button class="back-button" on:click={()=>openedStory=null}>← Back to stories</button><p class="micro-label">{storySource(openedStory).toUpperCase()} · {storyName(openedStory)}</p>{#if hasDeck}{@const cards=openedStory.cards.slice().sort((a,b)=>(a.sequence||0)-(b.sequence||0))}{@const currentCard=cards[storySlide]}<div class="story-deck">{#if cards.length>1}<div class="story-progress">{#each cards as _,index}<i class:active={index===storySlide}></i>{/each}</div>{/if}<article class={`story-slide deck-theme-${currentCard.theme||'CALM_CONTEXT'}`} on:touchstart={event=>(storyTouchStart=event.touches[0].clientX)} on:touchend={event=>endStorySwipe(event,cards.length)}>{#if currentCard.eyebrow}<p class="slide-eyebrow">{currentCard.eyebrow}</p>{/if}{#if currentCard.layout==='HERO_STAT'&&currentCard.components?.[0]}<div class="story-amount"><span>{currentCard.components[0].label}</span><strong>{currentCard.components[0].displayValue}</strong></div>{/if}<h1>{currentCard.title}</h1><p>{currentCard.body}</p>{#if currentCard.components?.length}<div class="observation-components">{#each currentCard.components as component}<div><span>{component.label}</span><strong>{component.displayValue}</strong></div>{/each}</div>{/if}{#each currentCard.actions||[] as action}{#if action.type==='OPEN_EVIDENCE'}<button class="story-action" on:click={()=>showStoryEvidence=true}>{action.label}</button>{:else if action.type==='OPEN_SALARY_OUTLOOK'}<button class="story-action" on:click={()=>{openedStory=null;openMoney();}}>{action.label}</button>{/if}{/each}</article>{#if cards.length>1}<div class="story-deck-controls"><button disabled={storySlide===0} on:click={()=>storySlide-=1}>←</button><span>{storySlide+1} of {cards.length}</span><button disabled={storySlide===cards.length-1} on:click={()=>storySlide+=1}>Next →</button></div>{/if}</div>{/if}</section></div>{/if}
<!-- svelte-ignore a11y_click_events_have_key_events -->
{#if showCommitmentReview}<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><button class="close" on:click={()=>showCommitmentReview=false}>×</button><p class="micro-label">MONTHLY COMMITMENT</p><h2>Help match this payment</h2><p class="module-reassurance">Your expense was saved normally. Link it only if it belongs to one of your commitments.</p>{#if commitmentReviewStatus==='loading'}<p>Loading payment choices…</p>{:else if commitmentReviewStatus==='error'}<p class="form-error">{commitmentError}</p>{:else}{#each commitmentReview as candidate}<div class="source-note"><strong>{money(candidate.amount)} · {candidate.category} / {candidate.subcategory}</strong><span>{dateLabel(candidate.transactionDate)}</span></div><p>Which commitment is this for?</p>{#each candidate.choices as choice}<button class="story-action" on:click={()=>resolveCandidate(candidate.transactionId,choice.id)} disabled={resolvingCandidate===candidate.transactionId}>{choice.label}</button>{/each}<button class="secondary" on:click={()=>resolveCandidate(candidate.transactionId,null)} disabled={resolvingCandidate===candidate.transactionId}>This is not a commitment</button>{/each}{#if !commitmentReview.length}<p>Everything is reviewed for this month.</p>{/if}{/if}</section></div>{/if}
{#if showStoryEvidence}<div class="modal-backdrop" on:click={()=>showStoryEvidence=false} on:keydown={(event)=>event.key==='Escape'&&(showStoryEvidence=false)} role="presentation"><section class="modal" on:click|stopPropagation role="dialog" aria-modal="true" tabindex="-1"><button class="close" on:click={()=>showStoryEvidence=false}>×</button><p class="micro-label">SUPPORTING EVIDENCE</p><h2>{openedStory?.evidence?.title||'Transactions behind this story'}</h2>{#if evidenceItems.length}<p class="evidence-total">{evidenceItems.length} {evidenceItems.length===1?'transaction':'transactions'}</p><div class="evidence-list">{#each evidenceItems as item}<div class="evidence-row"><div><strong>{item.merchant}</strong><span>{item.date}{item.date&&item.category?' · ':''}{item.category}</span></div><b>− {item.amount}</b></div>{/each}</div>{:else}<div class="empty-state evidence-empty"><span>◌</span><h2>No transactions attached</h2><p>This story does not include individual transactions to display.</p></div>{/if}</section></div>{/if}
{#if editing}<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" tabindex="-1"><button class="close" on:click={()=>editing=null}>×</button><p class="micro-label">AI-CAPTURED EXPENSE</p><h2>Edit transaction</h2><div class="source-note"><strong>Captured from your message</strong><span>Review the details below before saving.</span></div><label>Amount<input type="number" inputmode="decimal" min="0.01" step="0.01" bind:value={editAmount}/></label><label>Transaction date<input type="date" max={new Date().toISOString().slice(0,10)} bind:value={editDate}/></label>{#if optionsStatus==='loading'}<p class="edit-options-status">Loading categories, merchants, and accounts…</p>{:else if optionsStatus==='error'}<p class="form-error">{optionsError}</p>{:else}<label>Category<select value={editCategory} on:change={changeEditCategory}><option value="" disabled>Select a category</option>{#each editOptions.categories as option}<option value={option.name}>{option.name}</option>{/each}</select></label><label>Subcategory<select bind:value={editSubcategory} disabled={!editCategory}><option value="" disabled>Select a subcategory</option>{#each editSubcategories as option}<option value={option}>{option}</option>{/each}</select></label><label>Merchant<select bind:value={editMerchantId}><option value="" disabled>Select a merchant</option>{#each editOptions.merchants as option}<option value={String(option.id)}>{option.name}</option>{/each}</select></label><label>Source account<select bind:value={editAccountId}><option value="" disabled>Select an account</option>{#each editOptions.accounts as option}<option value={String(option.id)}>{option.name}</option>{/each}</select></label>{/if}{#if actionError}<p class="form-error">{actionError}</p>{/if}<div class="modal-actions"><button class="secondary" on:click={()=>editing=null}>Cancel</button><button class="primary" on:click={saveEdit} disabled={saving||optionsStatus!=='ready'}>{saving?'Saving…':'Save changes'}</button></div></section></div>{/if}
{#if deleting}<div class="modal-backdrop"><section class="modal" role="alertdialog" aria-modal="true" tabindex="-1"><p class="micro-label">DELETE TRANSACTION</p><h2>Delete {merchant(deleting)}?</h2><p>This updates the calendar and monthly totals.</p><div class="modal-actions"><button class="secondary" on:click={()=>deleting=null}>Cancel</button><button class="primary delete-confirm" on:click={confirmDelete}>Delete</button></div></section></div>{/if}
{#if handoff}<div class="modal-backdrop"><section class="modal whatsapp-handoff" role="dialog" aria-modal="true" tabindex="-1"><button class="close" on:click={()=>handoff=null}>×</button><p class="micro-label">WHATSAPP READY</p><h2>Continue in WhatsApp</h2><p>Send the missing transaction for {dateLabel(`${handoff.date}T12:00:00`)}.</p>{#if handoff.whatsappUrl}<a class="center-action whatsapp-action" href={handoff.whatsappUrl} target="_blank" rel="noopener">Open WhatsApp</a>{/if}<button class="auth-secondary" on:click={()=>handoff=null}>Done</button></section></div>{/if}
