import { expect, test } from '@playwright/test';

const api = 'http://localhost:8080';

async function startFromHome(page, request, instant) {
  expect((await request.post(`${api}/test/e2e/clock`, { data: { instant } })).ok()).toBeTruthy();
  const month = instant.slice(0, 7);
  await page.goto(`/dashboard?month=${month}`);
  const expectedMonth = new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' })
    .format(new Date(`${month}-01T12:00:00Z`)).toUpperCase();
  await expect(page.locator('.app-heading .micro-label')).toHaveText(expectedMonth);
}

async function openIncludedCommitments(page) {
  await page.locator('.story-carousel-card').first().click();
  const story = page.getByRole('dialog');
  await expect(story.getByRole('button', { name: 'Review' })).toHaveCount(0);
  await story.getByTestId('view-included-commitments').click();
  return page.getByRole('dialog').filter({ hasText: 'INCLUDED COMMITMENTS' });
}

test('frozen mutual-fund SIP lifecycle', async ({ page, request }) => {
  test.setTimeout(180000);
  const fixture = await request.post(`${api}/test/e2e/session`);
  expect(fixture.ok()).toBeTruthy();
  const { sessionToken } = await fixture.json();
  const headers = { Cookie: `WEB_SESSION=${sessionToken}` };
  await page.context().addCookies([{ name: 'WEB_SESSION', value: sessionToken, domain: 'localhost', path: '/', httpOnly: true }]);
  await startFromHome(page, request, '2026-04-15T09:00:00Z');
  await page.getByRole('button', { name: /Your money/ }).click();
  const missingHolding=await request.post(`${api}/api/web/mutual-funds`,{headers,data:{schemeCode:'holding-required-probe',schemeName:'Holding Required Probe Fund'}});
  expect(missingHolding.status()).toBe(400);
  await addFundThroughUi(page, 'Parag', 10000, 5);
  let response = await request.get(`${api}/api/web/mutual-funds`, { headers });
  let { mutualFunds: funds } = await response.json();
  const mistaken = funds[0];
  await page.getByRole('button', { name: `Open ${mistaken.schemeName} details` }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('dialog').filter({hasText:'FUND DETAILS'}).getByRole('button',{name:'Delete fund'}).click();
  await expect(page.locator('.mutual-funds-module:not(.stocks-module) .fund-card')).toHaveCount(0);
  await addFundThroughUi(page, 'Parag', 10000, 1);
  await addFundWithoutSipThroughUi(page, 'HDFC');
  await addFundThroughUi(page, 'Nippon', 30000, 10);
  response = await request.get(`${api}/api/web/mutual-funds`, { headers });
  ({mutualFunds: funds} = await response.json());
  const parag = funds.find(f=>f.schemeName.includes('Parag'));
  const hdfc = funds.find(f=>f.schemeName.includes('HDFC'));
  const nippon = funds.find(f=>f.schemeName.includes('Nippon'));
  expect(parag.activeSip.startMonth).toBe('2026-05');
  expect(nippon.activeSip.startMonth).toBe('2026-05');
  expect(hdfc.activeSip).toBeNull();
  expect(Number(hdfc.invested)).toBe(1000);
  expect(Number(hdfc.currentValue)).toBeGreaterThan(0);
  await page.locator('.money-modal > .close').click();
  await startFromHome(page, request, '2026-04-20T09:00:00Z');
  await page.getByRole('button', { name: /Your money/ }).click();
  await page.getByRole('button',{name:`Open ${hdfc.schemeName} details`}).click();
  await page.getByRole('dialog').filter({hasText:'FUND DETAILS'}).getByRole('button',{name:/Set SIP for/}).click();
  const setup=page.getByRole('dialog').filter({hasText:'Set up SIP for'});
  await setup.getByLabel('Monthly amount').fill('20000');
  await setup.getByLabel('SIP date').fill('5');
  await setup.getByLabel('Start month').fill('2026-05');
  await setup.getByRole('button',{name:'Save SIP'}).click();
  await page.getByRole('button',{name:`Open ${parag.schemeName} details`}).click();
  const earlySheet=page.getByRole('dialog').filter({hasText:'FUND DETAILS'});
  await expect(earlySheet.getByRole('button',{name:'Pay SIP'})).toBeDisabled();
  await expect(earlySheet.getByRole('button',{name:'Skip SIP'})).toBeDisabled();
  await earlySheet.getByRole('button',{name:'×'}).click();
  await page.locator('.money-modal > .close').click();
  await startFromHome(page, request, '2026-05-01T09:00:00Z');
  response=await request.get(`${api}/api/web/mutual-funds`,{headers});({mutualFunds:funds}=await response.json());
  expect(funds.find(f=>f.id===parag.id).currentSip.status).toBe('DUE');
  expect(funds.find(f=>f.id===hdfc.id).currentSip.status).toBe('SCHEDULED');
  const includedMay1=await openIncludedCommitments(page);
  const paragRow=includedMay1.getByTestId(`included-mutual-fund-commitment-${parag.id}`).locator('..');
  await expect(paragRow).toHaveClass(/due-commitment/);
  await expect(paragRow).toHaveClass(/due-fund-commitment/);
  await expect(paragRow).toHaveCSS('background-color','rgb(255, 244, 241)');
  await includedMay1.getByTestId(`included-mutual-fund-commitment-${parag.id}`).click();
  const focusedParag=page.getByRole('button',{name:`Open ${parag.schemeName} details`});
  await expect(focusedParag).toBeFocused();
  await expect(focusedParag).not.toHaveClass(/due-fund/);
  await expect(focusedParag).not.toHaveCSS('border-color','rgb(228, 164, 156)');
  await expect(focusedParag.locator('footer .fund-actions')).toHaveCSS('background-color','rgb(255, 244, 241)');
  await expect(focusedParag.locator('footer')).toContainText('Due now');
  await expect(focusedParag.locator('footer')).toContainText('View details');
  await expect(focusedParag).not.toContainText('Lump sum');
  await paySip(page,parag,11000,'2026-05-01',110,100);
  response=await request.get(`${api}/api/web/mutual-funds`,{headers});({mutualFunds:funds}=await response.json());
  expect(funds.find(f=>f.id===parag.id).currentSip.status).toBe('CONFIRMED');
  expect(Number(funds.find(f=>f.id===parag.id).activeSip.amount)).toBe(10000);
  expect(Number(funds.find(f=>f.id===parag.id).currentSip.units)).toBe(110);
  await page.locator('.money-modal > .close').click();
  const paidIncluded=await openIncludedCommitments(page);
  await expect(paidIncluded.getByTestId(`included-mutual-fund-commitment-${parag.id}`).locator('..')).not.toHaveClass(/due-commitment/);
  await startFromHome(page,request,'2026-05-05T09:00:00Z');
  const includedMay5=await openIncludedCommitments(page);
  const hdfcRow=includedMay5.getByTestId(`included-mutual-fund-commitment-${hdfc.id}`).locator('..');
  await expect(hdfcRow).toHaveClass(/due-commitment/);
  await hdfcRow.getByRole('button',{name:'Review'}).click();
  await expect(page.getByRole('button',{name:`Open ${hdfc.schemeName} details`})).toBeFocused();
  await page.getByRole('button',{name:`Open ${hdfc.schemeName} details`}).click();
  await page.getByRole('dialog').filter({hasText:'FUND DETAILS'}).getByRole('button',{name:'Skip SIP'}).click();
  const skip=page.getByRole('dialog').filter({hasText:'Skip SIP?'});
  await expect(skip).not.toContainText('penalty');
  const skipSaved=page.waitForResponse(r=>r.url().endsWith(`/api/web/mutual-funds/${hdfc.id}/sip-occurrences/2026-05/skip`) && r.request().method()==='POST');
  await skip.getByRole('button',{name:'Confirm skip'}).click();
  expect((await skipSaved).ok()).toBeTruthy();
  await expect(skip).toHaveCount(0);
  response=await request.get(`${api}/api/web/mutual-funds`,{headers});({mutualFunds:funds}=await response.json());
  expect(funds.find(f=>f.id===hdfc.id).currentSip.status).toBe('SKIPPED');
  expect(funds.find(f=>f.id===hdfc.id).currentSip.units).toBeNull();
  await page.getByRole('dialog').filter({hasText:'FUND DETAILS'}).getByRole('button',{name:'×'}).click();
  await page.locator('.money-modal > .close').click();
  await startFromHome(page,request,'2026-05-12T09:00:00Z');
  await page.getByRole('button',{name:/Your money/}).click();
  await paySip(page,nippon,30000,'2026-05-12',200,150);
  await page.locator('.money-modal > .close').click();
  await startFromHome(page,request,'2026-05-21T09:00:00Z');
  await page.getByRole('button',{name:/Your money/}).click();
  const lumpCard=page.getByRole('button',{name:`Open ${parag.schemeName} details`});
  await expect(lumpCard).not.toContainText('Lump sum');
  await lumpCard.click();
  await page.getByRole('dialog').filter({hasText:'FUND DETAILS'}).getByRole('button',{name:/Lump sum/}).click();
  const lump=page.getByRole('dialog').filter({hasText:'LUMP-SUM INVESTMENT'});
  await lump.getByLabel('Amount invested').fill('5000');
  await lump.getByLabel('Transaction date').fill('2026-05-21');
  await expect(lump.getByLabel('NAV')).toHaveCount(0);
  await lump.getByLabel('Units received').fill('50');
  const lumpSaved=page.waitForResponse(r=>r.url().endsWith(`/api/web/mutual-funds/${parag.id}/lump-sums`) && r.request().method()==='POST');
  await lump.getByRole('button',{name:'Add lump sum'}).click();
  expect((await lumpSaved).ok()).toBeTruthy();
  await expect(lump).toHaveCount(0);
  const sheet=page.getByRole('dialog').filter({hasText:'FUND DETAILS'});
  await expect(sheet).toContainText('₹17,000');
  await expect(sheet.getByRole('button',{name:'See full payment history'})).toHaveCount(0);
  await expect(sheet.locator('.investment-history').filter({hasText:'Payment history'})).toBeVisible();
  await expect(sheet).toContainText('Lump sum');
  const pnl=await sheet.locator('.detail-pnl').boundingBox();
  const lumpButton=await sheet.getByRole('button',{name:/Lump sum/}).boundingBox();
  expect(lumpButton.x).toBeGreaterThan(pnl.x+pnl.width-1);
  expect(Math.abs(lumpButton.y-pnl.y)).toBeLessThan(20);
  await expect(sheet).toContainText('₹11,000');
  await expect(sheet).toContainText('₹5,000');
  const paragDetails=await request.get(`${api}/api/web/mutual-funds/${parag.id}`,{headers});
  const paragData=await paragDetails.json();
  expect(Number(paragData.units)).toBe(170);
  expect(Number(paragData.invested)).toBe(17000);
  expect(paragData.history).toHaveLength(3);
  expect(Number(paragData.history.find(item=>item.kind==='SIP').nav)).toBe(100);
  expect(Number(paragData.history.find(item=>item.kind==='LUMPSUM').nav)).toBe(100);
  const skippedDetails=await request.get(`${api}/api/web/mutual-funds/${hdfc.id}`,{headers});
  const skippedData=await skippedDetails.json();
  expect(skippedData.history.find(item=>item.kind==='SIP')).toMatchObject({status:'SKIPPED',nav:null,units:null});
  await sheet.getByRole('button',{name:'Edit fund'}).click();
  const edit=page.getByRole('dialog').filter({hasText:'Scheme:'});
  await expect(edit.getByLabel('Scheme name')).toHaveCount(0);
  await edit.getByLabel('SIP frequency').selectOption('QUARTERLY');
  await edit.getByLabel('Effective month').fill('2026-06');
  await edit.getByLabel('Current NAV').fill('125');
  const planSaved=page.waitForResponse(r=>r.url().endsWith(`/api/web/mutual-funds/${parag.id}/plan`) && r.request().method()==='PATCH');
  await edit.getByRole('button',{name:'Save changes'}).click();
  expect((await planSaved).ok()).toBeTruthy();
  await expect(edit).toHaveCount(0);
  response=await request.get(`${api}/api/web/mutual-funds`,{headers});({mutualFunds:funds}=await response.json());
  expect(Number(funds.find(f=>f.id===parag.id).currentValue)).toBe(21250);
  expect(funds.find(f=>f.id===parag.id).activeSip.frequency).toBe('QUARTERLY');
  expect(funds.find(f=>f.id===parag.id).activeSip.nextDueDate).toBe('2026-08-01');
  const june=await request.get(`${api}/api/web/expenses/monthly?month=2026-06`,{headers});
  expect(june.ok()).toBeTruthy();
  const juneStory=(await june.json()).stories.find(story=>story.storyType==='MONTHLY_COMMITMENT');
  const juneEvidence=juneStory.evidence.byCard['next-commitment'];
  expect(juneEvidence.totalAmount.value).toBe(50000);
  const juneNames=juneEvidence.transactions.map(item=>item.merchantLabel);
  expect(juneNames).not.toContain(parag.schemeName);
  expect(juneNames).toContain(hdfc.schemeName);
  expect(juneNames).toContain(nippon.schemeName);
});
async function paySip(page,fund,amount,date,units,derivedNav){
  await page.getByRole('button',{name:`Open ${fund.schemeName} details`}).click();
  const sheet=page.getByRole('dialog').filter({hasText:'FUND DETAILS'});
  await expect(sheet.getByTestId(`fund-detail-sip-${fund.id}`)).toHaveClass(/due-sip/);
  await expect(sheet.getByTestId(`fund-detail-sip-${fund.id}`)).toHaveCSS('background-color','rgb(255, 244, 241)');
  const payButton=await sheet.getByRole('button',{name:'Pay SIP'}).boundingBox();
  const skipButton=await sheet.getByRole('button',{name:'Skip SIP'}).boundingBox();
  expect(skipButton.x).toBeGreaterThan(payButton.x);
  await sheet.getByRole('button',{name:'Pay SIP'}).click();
  const form=page.getByRole('dialog').filter({hasText:'CONFIRM SIP INVESTMENT'});
  await form.getByLabel('Amount invested').fill(String(amount));
  await form.getByLabel('Transaction date').fill(date);
  await expect(form.getByLabel('NAV')).toHaveCount(0);
  await form.getByLabel('Units received').fill(String(units));
  const paid=page.waitForResponse(r=>r.url().endsWith(`/api/web/mutual-funds/${fund.id}/sip-occurrences/2026-05/confirm`) && r.request().method()==='POST');
  await form.getByRole('button',{name:'Confirm payment'}).click();
  expect((await paid).ok()).toBeTruthy();
  await expect(form).toHaveCount(0);
  await expect(sheet).toContainText(`${Number(units).toFixed(3)} units`);
  await expect(sheet).toContainText(`NAV ₹${Number(derivedNav).toFixed(2)}`);
  await expect(sheet.locator('.due-sip')).toHaveCount(0);
  await expect(sheet.locator('.investment-history').filter({hasText:'Payment history'})).toContainText('2026-05 SIP');
  await sheet.getByRole('button',{name:'×'}).click();
}

async function addFundThroughUi(page, query, amount, sipDay) {
  await page.getByRole('button', { name: /Add a mutual fund/ }).click();
  const picker = page.getByLabel('Search and select scheme');
  await picker.fill(query);
  await page.locator('.scheme-menu button').first().click();
  await page.getByLabel('Monthly SIP amount').fill(String(amount));
  await page.getByLabel('SIP date').selectOption(String(sipDay));
  await page.getByLabel('Start month').fill('2026-04');
  await page.getByLabel('Current units').fill('10');
  await page.getByLabel('Total amount invested').fill('1000');
  await page.getByRole('button', { name: 'Add mutual fund' }).click();
  await expect(page.getByText('Your SIP is set up', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Done' }).click();
}

async function addFundWithoutSipThroughUi(page, query) {
  await page.getByRole('button', { name: /Add a mutual fund/ }).click();
  await page.getByLabel('Search and select scheme').fill(query);
  await page.locator('.scheme-menu button').first().click();
  await page.locator('fieldset').filter({ hasText: 'Do you have an actual SIP' }).getByLabel('No').check();
  await page.getByRole('button', { name: 'Add mutual fund' }).click();
  await expect(page.getByText('Enter current units and invested amount greater than zero.')).toBeVisible();
  await page.getByLabel('Current units').fill('10');
  await page.getByLabel('Total amount invested').fill('1000');
  await page.getByRole('button', { name: 'Add mutual fund' }).click();
  await expect(page.getByText('Your fund is ready', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Done' }).click();
}
